### ISSUE TITLE
SystemMPI easyblock

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#1091]
At the moment we have the `SystemCompiler` easyblock which can handle `GCC` and `Intel` compilers. An obvious extension would be to add a `SystemMPI` easyblock that could handle OpenMPI and MPICH variants (at first). This is important because MPI installations can be expected to be heavily tuned and the impact of ignoring this shouldn't be underestimated (it certainly affects scalability on large machines).

OpenMPI should be reasonably straightforward to implement. Trying to cover MPICH variants is harder because it will be harder to keep track of the environment variables they may use for performance tweaking.

In an ideal world, given `mpicc` you should be able to use the `SystemCompiler` and `SystemMPI` easyblocks to automatically construct an EasyBuild compatible toolchain.

**Comment by ocaisa** [comment]
Doing this for `IMPI` and `OpenMPI` seems straightforward, I guess I could create an easyblock for both that
- Gets the installation directory of the system implementation you wish to wrap
- Verify that you have a system compiler loaded that matches the one underlying the MPI implementation
- Run the appropriate sanity check
- Check the environment for variables that are relevant to the MPI implementation
- Create the module file and include setting the appropriate variables

**Comment by ocaisa** [comment]
Is the symlinking that's done at the end of the `impi` easyblock strictly necessary?

**Comment by boegel** [comment]
@ocaisa Your proposal looks sound, but you may run into some surprises when actually looking into it (like we did with `SystemCompiler`). You'll only know when you dive in. :)

I don't see any symlinking being done in the `impi` easyblock?

**Comment by ocaisa** [comment]
There's some at the end of the latest easyconfigs for `impi`

**Comment by ocaisa** [comment]
One thing I've seen is there is no way to query `impi` for the exact version, it only gives you the year. 
`OpenMPI` is much easier, `ompi_info` tells you the install dir, version, the compiler and version it was built with, currently doesn't even have an EasyBlock and all envvars are `OMPI_*`. I'll start with that.

**Comment by boegel** [comment]
Hmm, I'm not sure why those `ln -s` statements are in the `impi` easyconfigs, to be honest, and I can't seem to track it down either.

I have a faint memory that @damianam was involved with this, but I'm not sure...

**Comment by damianam** [comment]
I don't remember doing anything with `impi`, but I guess it could be related to this: https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/m/mpich.py#L147

**Comment by ocaisa** [comment]
Solved in https://github.com/easybuilders/easybuild-easyblocks/pull/1261
