### ISSUE TITLE
try-software-version for python bundle

### ISSUE THREAD

**Issue by ysagon** [easybuilders/easybuild-easyblocks#1103]
I tried to install Sphinx version 1.5.2 with try-software-version. The tar.gz that EB try to download is not the correct one.

I don't know the mechanism that is used to pull the correct url, but from what I understood, an index is downloaded:

    Downloaded file Sphinx_links.html from url https://pypi.python.org/simple/sphinx to /tmp/eb-UfLSHm/tmpogbQHf/Sphinx_links.html

and this index is parsed to get the correct url. Unfortunately the matched line seems to be wrong (from the log)

    https://pypi.python.org/packages/08/20/1509c3e01b08fba1cc24a74742b750cafc3a31a82d2a374aa54ff2ea0fd8/Sphinx-1.5.2.tar.gz was not found (HTTP response code 404), not trying again

The hash is not the correct one according to the sphinx_links.

The hash correspond to this line:

<a href="../../packages/08/20/1509c3e01b08fba1cc24a74742b750cafc3a31a82d2a374aa54ff2ea0fd8/Sphinx-1.5a2.tar.gz#md5=8ffddbfff0479a10c7fe6a66cc2bd708" rel="internal">Sphinx-1.5a2.tar.gz</a><br/>

instead of this one:

<a href="../../packages/e3/87/e271f7f0d498c7fdaec009c27955401d18ef357c0d468e1eb2be36bdc68c/Sphinx-1.5.2.tar.gz#md5=8a3068cd5dda49622b7eb5132d616e19" rel="internal">Sphinx-1.5.2.tar.gz</a><br/>

Here is how I tried to install Sphinx.
    
    eb  Sphinx-1.4.8-foss-2016a-Python-2.7.11.eb --try-software-version "1.5.2"

**Comment by boegel** [comment]
This problem should be fixed by https://github.com/easybuilders/easybuild-framework/pull/2225, which is in included in EasyBuild v3.3.0.
