### ISSUE TITLE
LDSHARED needs to be [re]defined for packages that use distutils

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-easyblocks#1136]
The background of the problem is that when python gets built `LDSHARED` gets defined in `$EBROOTPYTHON/lib/python2.7/_sysconfigdata.py`. If it is not overridden, that's the value used. That works fine in most cases. However, when mixing compilers (building Python with `GCCcore` but `pandas` with `icc`), that doesn't work, as the linker is `gcc`, but using intel flags.

We should consider explicitely setting the following variables in `PythonPackage.py`:

* `CC` (already done)
* `CXX` (already done)
* `OPT`
* `CFLAGS` (already done)
* `CCSHARED`
* `LDSHARED`
* `SO`
* `AR`
* `ARFLAGS`

**Comment by boegel** [comment]
@damianam Makes sense, I wasn't aware that these variables are picked up from the 'host' Python...

It definitely makes sense to define these additional environment variables, ideally via `prepare_step` (i.e. where the toolchain build environment is being set up).

**Comment by damianam** [comment]
Funny enough, I don't hit this issue for Python 3 packages.

**Comment by marscher** [comment]
https://github.com/python/cpython/pull/7914

**Comment by boegel** [comment]
We have an easy way now to fix `$LDSHARED` via `check_ldshared = True` in the easyconfig file (cfr. #1455), and we're looking into auto-fixing the value for recent Python versions in EasyBuild v4.0 (see #1788), so closing this...
