### ISSUE TITLE
Make Bundle of Rpackage extensions install the R packages in a library subdir as opposed to in the root of the installdir

### ISSUE THREAD

**Issue by pneerincx** [easybuilders/easybuild-easyblocks#1209]
In a complete R installation (plain vanilla R + extra packages) the R packages go into ${R_HOME}/library/, where ${R_HOME} is a subdir of ${EBROOTR}. When an R installation is devided into two easyconfigs:
* a plain vanilla R and
* an R bundle with extensions/packages
the extra R packages from the bundle end up in the root installdir of the bundle. E.g. in case the bundle would be named R-bundle with one R package named SomePackage it would be installed in  ${EBROOTRMINBUNDLE}/SomePackage. This is sub optimal, because the root installdir will also contain the easybuild subdir with installtion logs use easyconfig etc. and we don't want R to try to parse that as an R package. In addition you'd have to specify at least one package's subdir in the sanitycheck step:
```
sanity_check_paths = {
    'files': [],
    'dirs': ['SomePackage'],
}
```
This is a bit silly as the sanity of the Package is already checked by trying to load it in R, which is a more robust test. (`exts_filter = ("R -q --no-save", "library(%(ext_name)s)")`).
It would be better if the RPackage would always install the packages in a _library_ subdir both when used in a complete R easyconfig as well as in a Bundle easyconfig. We can then list:
```
sanity_check_paths = {
    'files': [],
    'dirs': ['library'],
}
```
as opposed to one or more random package sub dirs to satisfy sanity_check_paths.

**Comment by boegel** [comment]
follow-up in #1211
