### ISSUE TITLE
pip command in PythonPackage should reflect Python version

### ISSUE THREAD

**Issue by andreas-h** [easybuilders/easybuild-easyblocks#1232]
The `PythonPackage`easyblock doesn't check if it needs  to use `pip3` command  instead of `pip`, see https://lists.ugent.be/wws/arc/easybuild/2017-08/msg00051.html.

@boegel already gave a hint:

> I think is your actual problem...
> When you specify "use_pip = True", EasyBuild only tries to use 'pip', it doesn't take into account that it may need to use 'pip3' when Python 3 is being used... 
> 
> The logic for this is in the generic PythonPackage easyblock [1].
> 
> Are you up for taking a stab to fix that?
> Basically you need to do something like this when Python 3 is being used:
> 
>     self.install_cmd = self.install_cmd.replace('pip', 'pip3')
> 
> This should probably be done in the 'prepare_python' method, since only there the Python module used as a dependency will be loaded.

**Comment by andreas-h** [comment]
Following that advice, I would use `get_software_version` in case an EasyBuild Python module is used (btw., do I check against that with LooseVersion().startswith, or do you prefer something else?).

In  case system Python is used, it's more difficult, as there is no easy way of knowing if that's Python2 or Python3.  In that case I could simply check if there is *no* `pip` executable in the same path as python, and in that case check if there is `pip3` and use that and fail otherwise.  However, that feels a bit like a hack.

What do you think?

**Comment by boegel** [comment]
@andreas-h `get_software_version('Python')` is indeed the right approach here. You should directly compare `LooseVersion(python_ver)` with `LooseVersion('3')` rather than using `startswith`:

```python
python_ver = get_software_version('Python')
if python_ver:
    if LooseVersion(python_ver) >= LooseVersion('3'):
        self.log.info("<insert sensible log message here>")
        self.install_cmd = self.install_cmd.replace('pip', 'pip3')
        self.log.debug("<insert debug log statement showing new install cmd>")
else:
    # do something sensible here: what if Python version is not found? probably just log and stick to using `pip`?
```

In the light of the `else` part, maybe it's better to try and grab the Python version by running `python -V` as a command? That way, it will also work nicely if `python` is being picked up from the OS rather than being provided via EasyBuild...

**Comment by boegel** [comment]
Let's follow-up in #1235, no use in having two issues open for the same problem...
