### ISSUE TITLE
netCDF-4.3.3.1-foss-2016a requires m4

### ISSUE THREAD

**Issue by shawarden** [easybuilders/easybuild-easyblocks#1233]
When building netCDF-4.3.3.1-foss-2016a I get the following error:
```
...
FATALCannot find 'm4' utility. Install m4 and try again.
...
cd /resource/easybuild/build/netCDF/4.3.3.1/foss-2016a/netcdf-4.3.3.1/libsrc && m4 -DAPI=C -DNETCDF4=TRUE /resource/easybuild/build/netCDF/4.3.3.1/foss-2016a/netcdf-4.3.3.1/libsrc/netcdf.m4 > /resource/easybuild/build/netCDF/4.3.3.1/foss-2016a/netcdf-4.3.3.1/libsrc/netcdf.3
/bin/sh: m4: command not found
make[2]: *** [libsrc/CMakeFiles/manpage] Error 127
...
```
Editting netCDF-4.3.3.1-foss-2016a.eb's dependencies resolves the issue:
```
...
builddependencies = [
    ('CMake', '3.4.1'),
    ('Doxygen', '1.8.11'),
    ('M4', '1.4.17'), #needs m4 to compile?
]
...
```

But am I setting myself up for failures down the line?

**Comment by boegel** [comment]
Hmm, first time this pops up.

Your solution is OK, but it's generally better to include the `Autotools` bundle, where `M4` is being pulled in as a dependency of `Autoconf` that is included in the bundle, so I'd go with:

```python
builddependencies = [
    ...
    ('Autotools', '20150215'),
]
```

We should make this change in the existing `netCDF` easyconfigs...

**Comment by shawarden** [comment]
Thanks. I've adjusted mine to match.
