### ISSUE TITLE
CUDA on Power requires an rpm install

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#1264]
Currently, the CUDA easyblock expects to find a CUDA `runfile` install script. For X86_64 this is fine, but on Power you can only have RPMs (as far as I can tell).

**Comment by ocaisa** [comment]
For anyone who falls upon this issue, to install in a custom location from the rpm you need to do some pretty funky stuff:
```
#!/usr/bin/bash
source_rpm="$WORKDIR/EasyBuild/sources/c/CUDA/cuda-repo-rhel7-9-0-local-9.0.176-1.ppc64le-rpm"
install_dir="/pwrwork/rech/qgg/ums27nb/EasyBuild/software/CUDA/9.0.176"
cuda_short_version="9.0"
cuda_full_version="9.0.176-1"

# Derive some other variables
cuda_short_version_dash="${cuda_short_version/./-}"
cuda_rpm_version=$cuda_full_version.ppc64le
cuda_full_rpm_version=$cuda_short_version_dash-$cuda_rpm_version

# Keep track of where I start
current_dir=$PWD

# To unpack the original rpm
rpm2cpio $source_rpm | cpio -idmv

# To extract what I need to install
cd var/cuda-repo-$cuda_short_version_dash-local/
echo cuda-libraries-$cuda_full_rpm_version.rpm > initial_set
echo cuda-libraries-dev-$cuda_full_rpm_version.rpm >> initial_set
echo cuda-toolkit-$cuda_full_rpm_version.rpm >> initial_set
while read p; do rpm -qpR $p | grep cuda| grep -v warning| awk '{print $1}'| xargs -i ls {}-$cuda_rpm_version.rpm >> install_rpms; done < initial_set

# Now do the installation
cat install_rpms | xargs -i rpm -i --dbpath $install_dir/rpm  --relocate /usr/local/cuda-$cuda_short_version=$install_dir --relocate /usr/lib64/pkgconfig=$install_dir/pkgconfig --nopre --nopost --nodeps --ignorearch {}

# The runtime is not relocatable but we only care about the library files inside, not the soft links to them
mkdir rt
cd rt
rpm2cpio ../cuda-cudart-$cuda_full_rpm_version.rpm | cpio -idmv
cp usr/local/cuda-$cuda_short_version/targets/ppc64le-linux/lib/lib* $install_dir/lib64

# The samples are also not relocatable, but again we only care about the files inside
cd ..
mkdir samples
cd samples
rpm2cpio ../cuda-samples-$cuda_full_rpm_version.rpm | cpio -idmv
cp -r usr/local/cuda-$cuda_short_version/samples $install_dir/
cp usr/local/cuda-$cuda_short_version/bin/* $install_dir/bin

# clean up
cd $current_dir

rm -rf etc var
```
..but at least things seem to work afterwards.

**Comment by ocaisa** [comment]
@boegel I'd like to make a PR for a toolchain on an OpenPower system that has Spectrum MPI and CUDA support but this is going to be a blocker. I'm happy to first make a non-CUDA  toolchain PR for the other components but do you have any tips about how I will deal such a funky install (or how I can rewrite this in a more python-ic way)?

**Comment by boegel** [comment]
@ocaisa Targeting a toolchain for OpenPOWER without CUDA is definitely a first step imho, taking small steps helps in actually making progress.

The most annoying thing other than relying on `rpm2cpio` and `cpio` to unpack the RPMs is querying the RPMs, but I guess running `rpm -q` commans suffices.

Since this is such a mess, have you reached out to NIVIDIA support to ask why things are so dire on POWER compared to x86_64?

**Comment by ocaisa** [comment]
I've opened a feature request https://developer.nvidia.com/nvidia_bug/2008428 and am in touch the JSC NVIDIA contact about it.

**Comment by Flamefire** [comment]
CUDA now provides a runscript for Power although the 10.1.243 one is broken

**Comment by ocaisa** [comment]
Great! Closing...
