### ISSUE TITLE
undefined variable in scalapack

### ISSUE THREAD

**Issue by olesenm** [easybuilders/easybuild-easyblocks#1319]
In develop:

    File "/home/mol/Software/easybuild/easybuild-easyblocks/easybuild/easyblocks/s/scalapack.py", line 210, in build_step
    (out, _) = run_cmd(cmd, path=path, log_ok=False, log_all=True, simple=False, log_output=verbose)
    NameError: global name 'path' is not defined

https://github.com/easybuilders/easybuild-easyblocks/blob/5a3cd4918d18f131714431cacbab96f8caf16f92/easybuild/easyblocks/s/scalapack.py#L210

**Comment by boegel** [comment]
Hmm, this slipped in with #1288.

The strange thing is that I haven't been hit by this, despite it being a clear problem and testing with that updated easyblock... 😕 

cc @akesandgren

**Comment by akesandgren** [comment]
Should be fixed in PR #1320 

Made a C&P error when copying things from configuremake.py

**Comment by boegel** [comment]
OK, now I am seeing it, I probably tested #1288 with an earlier version of the updated easyblock somehow, ugh. Fixed in #1321.

**Comment by boegel** [comment]
Thanks for reporting this @olesenm, we shouldn't have missed this...
