### ISSUE TITLE
Changes to Qt easyblock needed for Qt 5.9.*

### ISSUE THREAD

**Issue by klust** [easybuilders/easybuild-easyblocks#1322]
Somewhere between versions 5.8.0 and 5.9.3 of Qt, the questions asked at the start of the configure process have changed slightly, causing the current easyblock to fail for version 5.9.3. In particular, line 86 of qt.py does not work anymore for 5.9.3. It works for me when I replace with 
`"Which edition of Qt do you want to use?": 'o'`
but of course there is more needed to guarantee that the easyblock still works with earlier versions.

**Comment by boegel** [comment]
fixed in #1328
