### ISSUE TITLE
CUDA < 8 fails to build

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyblocks#1345]
I tried to build old CUDA versions (for nostalgic purposes) but it fails during the sanity check. The problem is that the installation directory doesn't contain any files:

```
$ eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/easybuild/test CUDA-6.5.14.eb -dr
== temporary log file in case of crash /tmp/eb-rWXqtI/easybuild-5FWXJK.log
== resolving dependencies ...
== processing EasyBuild easyconfig /easybuild/test/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.0-py2.7.egg/easybuild/easyconfigs/c/CUDA/CUDA-6.5.14.eb
== building and installing CUDA/6.5.14...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/CUDA/6.5.14/dummy-dummy): build failed (first 300 chars): Sanity check failed: no file of ('bin/fatbinary',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/nvcc',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/nvlink',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/ptx
== Results of the build can be found in the log file(s) /tmp/eb-rWXqtI/easybuild-CUDA-6.5.14-20180116.082126.YVJun.log
ERROR: Build of /easybuild/test/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.0-py2.7.egg/easybuild/easyconfigs/c/CUDA/CUDA-6.5.14.eb failed (err: "build failed (first 300 chars): Sanity check failed: no file of ('bin/fatbinary',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/nvcc',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/nvlink',) in /easybuild/test/software/CUDA/6.5.14, no file of ('bin/ptx")
$ ls /easybuild/test/software/CUDA/6.5.14
# nothing
```

Here is the log file: [easybuild-CUDA-6.5.14-20180116.082126.YVJun.log](https://github.com/easybuilders/easybuild-easyblocks/files/1634568/easybuild-CUDA-6.5.14-20180116.082126.YVJun.log)

The line `== 2018-01-16 08:22:01,223 run.py:367 DEBUG run_cmd_qa cmd perl ./cuda-installer.pl -verbose -silent -toolkitpath=/easybuild/test/software/CUDA/6.5.14 -toolkit : read failed: Other end disconnected!` probably says that the [qanda stuff](https://github.com/easybuilders/easybuild-easyblocks/blob/master/easybuild/easyblocks/c/cuda.py#L79) is wrong? If so why doesn't the `failed` trigger an error in this step (`install`)?

**Comment by boegel** [comment]
@SethosII Sorry for not picking up on this...

Which OS (version) was this on?
Older CUDA versions are known not to install on new OS versions (like CentOS 7.x).

**Comment by SethosII** [comment]
@boegel No worries. This is on Ubuntu 16.04.

**Comment by boegel** [comment]
The most likely problem is that the CUDA installer doesn't like the GCC version installed in the system. If it's too new, it'll just refuse to install.

EasyBuild doesn't detect the problem during installation because the installer just exists with zero exit code...

**Comment by SethosII** [comment]
Ok, that seems plausible, I found this list for supported CUDA and GCC versions: https://stackoverflow.com/a/6622751/7558731. The GCC version of `foss/2016b` is indeed not supported for CUDA < 8.
