### ISSUE TITLE
EasyBuild/3.5.3, MPICH-3.2-GCC-4.9.3-2.25.eb, mpich.py, sanity checks fail

### ISSUE THREAD

**Issue by pmatousu** [easybuilders/easybuild-easyblocks#1400]
== temporary log file in case of crash /tmp/eb-_sVvMd/easybuild-o4FM2v.log
     
     WARNING: Found one or more non-allowed loaded (EasyBuild-generated) modules in current environment:
     * GCCcore/4.9.3
     * GCCcore/4.9.3
     * ncurses/6.0-GCCcore-4.9.3
     * CMake/3.6.1-GCCcore-4.9.3
     * binutils/2.25-GCCcore-4.9.3
     
     This is not recommended since it may affect the installation procedure(s) performed by EasyBuild.
     
     To make EasyBuild allow particular loaded modules, use the --allow-loaded-modules configuration option.
     To specify action to take when loaded modules are detected, use --detect-loaded-modules={error,ignore,purge,unload,warn}.
     
     See http://easybuild.readthedocs.io/en/latest/Detecting_loaded_modules.html for more information.
     
     == resolving dependencies ...
     == processing EasyBuild easyconfig /home/petrm/opt/eb/software/EasyBuild/3.5.3/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.3-py2.7.egg/easybuild/easyconfigs/m/MPICH/MPICH-3.2-GCC-4.9.3-2.25.eb
     == building and installing MPICH/3.2-GCC-4.9.3-2.25...
     == fetching files...
     == creating build dir, resetting environment...
     == unpacking...
     == patching...
     == preparing...
     == configuring...
     == building...
     == testing...
     == installing...
     == taking care of extensions...
     == postprocessing...
     == sanity checking...
     == FAILED: Installation ended unsuccessfully (build directory: /home/petrm/Documents/build/eb/build/MPICH/3.2/GCC-4.9.3-2.25): build failed (first 300 chars): Sanity check failed: no (non-empty) directory of ('lib',) in /home/petrm/opt/eb/software/MPICH/3.2-GCC-4.9.3-2.25
     == Results of the build can be found in the log file(s) /tmp/eb-_sVvMd/easybuild-MPICH-3.2-20180417.160551.CiUSK.log
     ERROR: Build of /home/petrm/opt/eb/software/EasyBuild/3.5.3/lib/python2.7/site-packages/easybuild_easyconfigs-3.5.3-py2.7.egg/easybuild/easyconfigs/m/MPICH/MPICH-3.2-GCC-4.9.3-2.25.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory of ('lib',) in /home/petrm/opt/eb/software/MPICH/3.2-GCC-4.9.3-2.25")

Again lib instead lib64. in mpich.py block.

**Comment by boegel** [comment]
@pmatousu Should be fixed with #1403, please check?

**Comment by pmatousu** [comment]
Yes, this worked for me (I just did not use both lib and lib64), the change worked and build was successful. So suggested change will work.

**Comment by boegel** [comment]
@pmatousu OK, thanks for confirming.

BTW, you can usually run `eb --module-only` after you've fixed the sanity check in either the easyconfig or the easyblock, you don't need to restart the whole installation...

**Comment by boegel** [comment]
#1403 merged, so closing this, thanks for reporting @pmatousu!
