### ISSUE TITLE
The TensorFlow easyblock should require cuDNN when CUDA is enabled

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyblocks#1445]
At the moment the TF easyblock does not enforce the presence of `cuDNN` when `CUDA` is enabled.

**Comment by boegel** [comment]
@akesandgren Up for this?

**Comment by akesandgren** [comment]
Would a EasyBuildError("TensorFlow have a strict dependency on cuDNN if CUDA is enabled")
message be ok, or do you want another text.

**Comment by boegel** [comment]
@akesandgren with `s/have/has/g`, ok for me

**Comment by akesandgren** [comment]
Solved, together with a couple of other minor things, in PR #1453
