### ISSUE TITLE
Python easyblock doesn't add the correct include dir to $CPATH

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1446]
The python easyblock only add $EBROOTPYTHON/include to CPATH, but the Python include files are in
$EROOTPYTHON/include/python%(pyver)s

This makes some codes fail in compilation.

**Comment by boegel** [comment]
@akesandgren Do you have an example of something that fails because of this?

It's a bit strange this has never popped up before...

**Comment by akesandgren** [comment]
Scipion (or rather Xmipp inside Scipion) fails to find Python.h.
Since that uses SCons it would normally use the system python and link stuff to its internal tree and thus bypass the problem.

I don't know of any other examples at the moment. But the current CPATH add from python.py just uses ConfigureMakes rule for CPATH additions.

Adding include/%(pyver)s may well break stuff though, for instance if something has a dep-chain that pulls in multiple python versions. But if it does I would say that the dependency chain, for whatever it is that gets broken, is then broken in itself.

I know that the preferred style is to either have explicit -Ipython-path/include/pythonx.y or have
#include <pythonx.y/something.h>
but I see lots of code that don't follow the rules (in general that is)

**Comment by mstud** [comment]
Another example where this fails would be LAMMPS with the PYTHON package enabled (even though #594 is not officially in yet):
```
../pair_python.cpp:18:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.

```

**Comment by boegel** [comment]
@akesandgren I'm not sure we should risk breaking stuff by always adding `include/pythonX.Y` to `$CPATH`...

I'm more inclined to only do so for software where it's really needed, like `Xmipp` or `LAMMPS`, since there the fix is pretty straightforward. While if software starts failing to build because we have included it through the `Python` module, it may be a lot harder to resolve those issues?

@mstud Can you mention that in #594 explicitly?

**Comment by mstud** [comment]
Also note that `include/%(pyver)s` won't be enough in case of Python 3, there you also may need to add the abiflags to the version, e.g. `include/python3.6m`

**Comment by boegel** [comment]
@mstud Good point, that does probably mean we should provide a function in `Python.py` that other easyblocks can leverage to determine the (full) include path...

**Comment by akesandgren** [comment]
Well, I don't really think there is a risk to add include/%(pyver)s (or similar for P3) to CPATH.
Code that handles this themselves would either explicitly add -I.../include/python2.7, or have #include <python2.7/something.h> or similar.

The only real risk is include file name clashing, but that could happen anyway.

I've been running with that for a while (manually added) and have not seen any problems.
Although i haven't built that many packages with the toolchain where CPATH got include/python2.7 in it.

**Comment by JackPerdue** [comment]
While experimenting with #594 (and associated easyconfigs) I found this disturbing (and wrong):
[j-perdue@tlogin-0502 (18:47) ~]$ python3-config --includes
-I/general/general/sw/eb/sw/Python/3.6.3-foss-2017b/include/python3.6m -I/general/general/sw/eb/sw/Python/3.6.3-foss-2017b/include/python3.6m
[j-perdue@tlogin-0502 (18:47) ~]$ pkg-config python3 --cflags
-I/sw/eb/sw/Python/3.6.3-foss-2017b/include/python3.6m 
the former stems from some of the symlinks we have for GPFS but /general/general is just wrong (one /general would work though... the pkg-config output is prettier)

Changed things to use pkg-config (will provide info in #594)

**Comment by boegel** [comment]
re-opening this since the change from #1619 got reverted in #1620 due to problems with `ROOT`
