### ISSUE TITLE
HDF5 lacks pkgconfig files

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1450]
At least Ubuntu packaging of HDF5 contains pkgconfig files for HDF5. The EB build doesn't add any which causes some codes to find the OS-installed hdf5 instead.
The Ubuntu pkgconfig files are an addition to HDF5, but they should be fairly easy to create on the fly.

**Comment by boegel** [comment]
@akesandgren Any reference to how this is done in Ubuntu?

**Comment by akesandgren** [comment]
They just add prewritten (well a sed 's/@MULTIARCH@/$(DEB_HOST_MULTIARCH)/g' is used on the template) hdf5.pc files to /usr/lib/pkgconfig.
Nothing fancy, should be trivial to do inside the easyblock.

**Comment by boegel** [comment]
fixed in #1504
