### ISSUE TITLE
CUDA stubs path missing

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyblocks#1463]
In order for the NVML and other libraries to be found, one needs to add 
$CUDA_ROOT/lib64/stubs to $LIBRARY_PATH (not $LD_LIBRARY_PATH)

**Comment by AndiH** [comment]
That is, in cases where the CUDA driver is not installed on the node where the compilation happens.

**Comment by ocaisa** [comment]
That was recently reported in https://github.com/easybuilders/easybuild-easyconfigs/issues/6602
Is there perhaps a race to see who will issue the PR first? :P

**Comment by surak** [comment]
@ocaisa sorry, I should have searched better. Do I close this one then? Andreas is doing the PR as I write.

**Comment by AndiH** [comment]
@ocaisa In our non-easybuild-controlled cluster we also set the following variables. I was unsure how to include them now into the `cuda.py` easyblock, since they are opening a whole new set full of `bin` and `lib` variables.

Suggestions? I can gladly modify the PR.

```
prepend_path("PATH","/gpfs/software/opt/cuda/9.1.85/nvvm/bin")
prepend_path("INCLUDEPATH","/gpfs/software/opt/cuda/9.1.85/nvvm/include")
prepend_path("CPATH","/gpfs/software/opt/cuda/9.1.85/nvvm/include")
prepend_path("LIBRARY_PATH","/gpfs/software/opt/cuda/9.1.85/nvvm/lib64")
prepend_path("LD_LIBRARY_PATH","/gpfs/software/opt/cuda/9.1.85/nvvm/lib64")
```

**Comment by ocaisa** [comment]
I  assume that these are only in recent cuda versions? If so you could do a conditional extension of the list of guesses (like is already done at https://github.com/easybuilders/easybuild-easyblocks/blob/master/easybuild/easyblocks/c/cuda.py#L160)

**Comment by AndiH** [comment]
The furthest back JURECA goes is to CUDA 7. I don't have any other machine with older CUDA versions. I'll add it in the same manner!

**Comment by AndiH** [comment]
Added! I also changed the suggested `os.join.path()` because AFAIK it does not work on lists, or does it?

**Comment by ocaisa** [comment]
Thanks for the fix. I'll take a look at the PR tomorrow.

**Comment by damianam** [comment]
I am closing this issue, as it has been solved in https://github.com/easybuilders/easybuild-easyblocks/pull/1464
