### ISSUE TITLE
MATLAB: Check on the compiler mcc, even though it's a separate toolbox/license?

### ISSUE THREAD

**Issue by crubb** [easybuilders/easybuild-easyblocks#1478]
Hey,

https://github.com/easybuilders/easybuild-easyblocks/blob/bbb0de796ad430b20cb98aaff11b80d4739e0422/easybuild/easyblocks/m/matlab.py#L152-L154

In these lines, checks are done for the MATLAB Compiler (mcc), which seems to be a paid license and may not be available to everyone.

Would it make sense to remove the mcc checks?

Best,
crubb

**Comment by boegel** [comment]
@crubb Sure, that's a bit too restrictive indeed... Up for issues a PR for it?

**Comment by boegel** [comment]
fixed in #1514
