### ISSUE TITLE
Tensorflow doesn't pick up on EB opt-flags when building the core parts

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1508]
The 'CC_OPT_FLAGS': os.getenv('CXXFLAGS'), setting in tensorflow.py is only propagated to the building of externals. When building the actual tensorflow core parts it is not used.

I have been unable (so far) to figure out why it isn't picked up in the core while still showing up in externals (like boringssl).

**Comment by mboisson** [comment]
At an Intel Workshop, they pointed us to https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

in which they recommend the following line to compile TF
`bazel build --config=mkl -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512er //tensorflow/tools/pip_package:build_pip_package`

**Comment by akesandgren** [comment]
Ok, we can close this.

After a lot of searching and sha256sum checking I've been able to determine that the objects/.so's that end up in the installed wheel are coming from the compiles that uses -xHost or rather EB's CXXFLAGS setting from the 'CC_OPT_FLAGS': os.getenv('CXXFLAGS'), line in tensorflow.py.

So all is well.
