### ISSUE TITLE
PythonPackage pip install should not write in $HOME/.cache

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1511]
We should try to avoid writing in $HOME as much as possible. One step would be to stop pip install from doing it.

**Comment by boegel** [comment]
@akesandgren Looks like this is quite easy to do: just pass `--no-cache-dir` to `pip`. Or set `$XDG_CACHE_HOME`, see https://pip.pypa.io/en/stable/reference/pip_install/#caching.

The latter is probably better/safer, unless we check when `--no-cache-dir` was added and we check the `pip` version.

**Comment by akesandgren** [comment]
According to that url --no-cache-dir was added with v6.0 when the cache was first invented.

**Comment by akesandgren** [comment]
Not sure where in pythonpackage it is best to set XDG_CACHE_HOME.
It need to be set even before test_step since the result of compose_install_command is used there too.

**Comment by boegel** [comment]
fixed with #1687

**Comment by surak** [comment]
Is there an option, like sourcepath, but for pip? We are running into the problem where the compute nodes don't have network access, and the ones which do, have no gpu.
