### ISSUE TITLE
Tensorflow easyblock should probably use --install_base  and --output_user_root

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1515]
Should perhaps set --install_base  and --output_user_root too, bazel still uses $HOME/.cache/bazel for some things.

Needs investigation.

**Comment by akesandgren** [comment]
Ok, seems to work, but bazel still creates $HOME/.cache/bazel/_bazel_username/
Nothing is stored there (after adding the above args to bazel), but it is still annoying.

**Comment by boegel** [comment]
@akesandgren Can we consider this fixed via #1519? I don't think that Bazel create the empty `$HOME/.cache/bazel/_bazel_$USER` directory is too big of a problem...

**Comment by akesandgren** [comment]
Yeah, the main problem is solved. Making sure it doesn't create the dir can probably only be handled by explicitly setting $HOME before calling bazel...

**Comment by boegel** [comment]
@akesandgren Well, that's worth considering...
