### ISSUE TITLE
Use of --ignore-installed in TensorFlow's step_install

### ISSUE THREAD

**Issue by agijsberts** [easybuilders/easybuild-easyblocks#1536]
TensorFlow's EasyBlock installs the produced wheel package via
``pip install --ignore-installed``

https://github.com/easybuilders/easybuild-easyblocks/blob/4f816688b92748d0fcd40ae553fb2dcd369c965a/easybuild/easyblocks/t/tensorflow.py#L372

As a consequence, it pulls in binary wheels of all dependencies, including for example NumPy. So loading the TensorFlow module will replace the NumPy as part of the Python package (linked against MKL in my case) with a precompiled NumPy linked against a pre-shipped OpenBLAS. Is this intended behavior?

At least on our systems, removing ``--ignore-installed`` leads to desired behavior, i.e. pip does not install those dependencies that were already satisfied via dependent modules.

**Comment by boegel** [comment]
@agijsberts That's by no means intended, we overlooked this completely... Thanks a lot for reporting this!

The `--ignore-installed` was added in the original implementation of the `TensorFlow` easyblock to try and ensure the specified `*.whl` is installed, cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1287 .

We probably also need to use `--no-deps` to avoid that `pip` pulls in all dependencies, there should be no need for that, everything should be in place already (and if not, that should be fixed).

cc @akesandgren

**Comment by agijsberts** [comment]
Thank you for confirming my suspicion.

Mind that the pip command does pull in tensorboard, which is obviously an important dependency. I guess you mean that tensorboard (and maybe a couple of other libraries) should be pulled in via the extensions mechanism (**exts_list**)?

**Comment by boegel** [comment]
@agijsberts Indeed, we'll need to fix this in the existing `TensorFlow` easyconfigs, but that should be just a matter of including everything that is needed via `exts_list`, indeed...

**Comment by boegel** [comment]
Fixed in #1537, where `--no-deps` is used if extensions are included in the `TensorFlow` easyconfig file (i.e. if `exts_list` is not empty).

See also updated easyconfigs for TensorFlow 1.10.x in https://github.com/easybuilders/easybuild-easyconfigs/pull/6940
