### ISSUE TITLE
Make CMakeMake easyblock immune to system boost.

### ISSUE THREAD

**Issue by bartoldeman** [easybuilders/easybuild-easyblocks#1608]
As mentioned in 
https://github.com/easybuilders/easybuild-easyconfigs/pull/7149
if an old boost-devel rpm installed on CentOS6:
```
boost-devel-1.41.0-25.el6.centos.x86_64

$ rpm -ql boost-devel-1.41.0-25.el6.centos.x86_64 | grep -i cmake
/usr/lib64/boost/Boost-relwithdebinfo.cmake
/usr/lib64/boost/Boost.cmake
/usr/lib64/boost/BoostConfig.cmake
/usr/lib64/boost/BoostConfigVersion.cmake

-- Boost  found.
Boost Include: /usr/include
Boost Linkdir: /usr/lib64
```
then anything that combines cmake and boost gets confused by this as the EB boost does not include any cmake files.

adding `-DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON`
avoids this.

ref:
https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake
(which shows that if it finds a Boost-cmake config file, it's game over)
https://cmake.org/cmake/help/v3.12/module/FindBoost.html

**Comment by vanzod** [comment]
Solved with #1618
