### ISSUE TITLE
Sanity checks fail for OpenCV 4.0.1 because of obsolete tools

### ISSUE THREAD

**Issue by juriroemer** [easybuilders/easybuild-easyblocks#1622]
OpenCV Easyblock checks (and fails) for createsamples and traincascade, which are no longer in use in current OpenCV versions. See https://github.com/opencv/opencv/issues/13231 and http://answers.opencv.org/question/207121/why-createsamples-traincascade-applications-are-not-built-when-building-opencv-401/

**Comment by ocaisa** [comment]
This has been fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1616 and will be included in 3.8.1 which is hopefully out this week,

**Comment by juriroemer** [comment]
Didn't see that, thank you.
