### ISSUE TITLE
CUDA_{ROOT,HOME,PATH} are PATH-like?

### ISSUE THREAD

**Issue by bertwesarg** [easybuilders/easybuild-easyblocks#1662]
See: https://github.com/easybuilders/easybuild-easyblocks/blob/e3a4cd70357103e1fa463751df13378f217c7ad1/easybuild/easyblocks/c/cuda.py#L191-L193

This creates `prepend_path` module commands, instead of `setenv`! Is there a particular reason to do so?

**Comment by akesandgren** [comment]
Doh, that's wrong, at least for HOME and ROOT, not sure what CUDA_PATH is used for.

**Comment by boegel** [comment]
Looks like `$CUDA_PATH` should also be set via `setenv`, see https://docs-cupy.chainer.org/en/stable/install.html#install-cuda .

**Comment by ocaisa** [comment]
I'm MotW, I'll make a PR for that now

**Comment by boegel** [comment]
@bertwesarg Thanks a lot for reporting this!

How did you notice that these environment variables were set incorrectly via `prepend_path` rather than `setenv`? Did you run into some problem because of it, or did you just happen to notice?

**Comment by boegel** [comment]
@ocaisa Should be done via `make_module_extra`

**Comment by bertwesarg** [comment]
> @bertwesarg Thanks a lot for reporting this!
> 
> How did you notice that these environment variables were set incorrectly via `prepend_path` rather than `setenv`? Did you run into some problem because of it, or did you just happen to notice?

More or less by accident. I noticed on our system that the `refcount` variable is set, than looked into the modules file, notified our support, and they told me, its coming from easybuild.

**Comment by boegel** [comment]
fixed in #1663, thanks again for reporting @bertwesarg!
