### ISSUE TITLE
ModuleRC easyblock must not blindly overwrite existing modulerc.lua

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#1699]
If the existing .modulerc.lua for Java contains
module_version("Java/1.8.0_181", "1.8")
then modulerc easyblock must not blindly overwrite it when installing Java-11.eb
It must ADD module_version("Java/11.0.2", "11") 

And it should also make sure to put a \n at the end of each line.

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-framework/pull/2848
