### ISSUE TITLE
Build of X11 broken with merge of PR #1817

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyblocks#1820]
The build of `X11-20190717-GCCcore-8.3.0.eb` fails with error message `Failed to read ./configure: [Errno 2] No such file or directory: './configure'` for its components. The `preconfigopts` already present in the easyconfig seems to not be applied to the components.

This build breaks with commit c2f387fb9efd10d3dc151a98e14a2f767406f8d4.
Previous merge with commit 1494af7cba04218c9288cce9a6b9c6180498cc05 does **not** show this problem.

**Comment by lexming** [comment]
PR #1821 fixes this issue

**Comment by boegel** [comment]
#1821 merged, so closing... Thanks for reporting this @lexming!
