### ISSUE TITLE
pylibdir of versionindependentpythonpackage.py is overwritten by pythonpackage.py

### ISSUE THREAD

**Issue by sluehrs** [easybuilders/easybuild-easyblocks#1846]
In 599869d `set_pylibdirs` of [pythonpackage.py](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/pythonpackage.py) was changed to always set `self.pylibdir` (not only if its value is `UNKNOWN`). This seems to break the `prepare_step` of [versionindependentpythonpackage.py](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/versionindependentpythonpackage.py) because pylibdir is now overwritten. This forces the `install_step` to crash afterwards due to missing subdirs within the `os.mkdir(full_pylibdir)` command.

**Comment by boegel** [comment]
Problem reproduced with `JUBE-2.0.5.eb` (which escaped our regression text), fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/1924
