### ISSUE TITLE
NCL intel and netcdf libdirs are set incorrectly by the EasyBlock

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-easyblocks#1858]
**Issue**
We are using EasyBuild's RPATH support. Thus, EasyBuild does an RPATH sanity check where LD_LIBRARY_PATH is emptied, and EasyBuild checks if all binaries can still find their respective libraries. This failed for the NCL-6.6.2-intel-2018b.eb for various libraries:

```
libnetcdf.so.13 => not found
libiomp5.so => not found
libifcore.so.5 => not found
libifport.so.5 => not found
libpng16.so.16 => not found
libjpeg.so.8 => not found
```

The latter two are because of missing dependencies, which has to be fixed on the EasyConfig side (see https://github.com/easybuilders/easybuild-easyconfigs/issues/9332). The first four are because of the way that the NCL EasyBlock passes the library path (i.e. the paths passed with ```-L``` to the linker). 

**Issue with the intel libs**

From the current EasyBlock:

```
ifort = get_software_root('ifort')
if LooseVersion(get_software_version('ifort')) < LooseVersion('2011.4'):
                ctof_libs = '-lm -L%s/lib/intel64 -lifcore -lifport' % ifort
            else:
                ctof_libs = '-lm -L%s/compiler/lib/intel64 -lifcore -lifport' % ifort
```

However, the ```ifort``` directory structure is:

```
$EBROOTIFORT/compilers_and_libraries/linux/lib/intel64
```

**Proposed fix for intel libs**
Replace the ```ctof_libs``` in the else statement with

```
else:
                ctof_libs = '-lm -L%s/compilers_and_libraries/linux/lib/intel64/ -lifcore -lifport' % ifort
```

**Issue with the netCDF libs**
Libdirs are automatically for

```
deps = ["HDF5", "JasPer", "netCDF", "HDF", "g2lib", "g2clib", "Szip", "UDUNITS"]
```
by this part:
```
for dep in deps:
            root = get_software_root(dep)
            if not root:
                raise EasyBuildError("%s not available", dep)
            libs += ' -L%s/lib ' % root
            includes += ' -I%s/include ' % root
```
Something similar is done for optional dependencies, ```opt_deps = ["netCDF-Fortran", "GDAL"]```.

The problem is that for netCDF, I only have a ```libs64``` directory:

```
[casparl@int2 ~]$ ls -al $EBROOTNETCDF
total 28
drwxr-sr-x 7 jenkins jenkins 4096 Jul  4 15:09 .
drwxr-sr-x 4 jenkins jenkins 4096 Jul  4 15:31 ..
drwxr-sr-x 2 jenkins jenkins 4096 Jul  4 15:09 bin
drwxr-sr-x 3 jenkins jenkins 4096 Jul  4 15:09 easybuild
drwxr-sr-x 2 jenkins jenkins 4096 Jul  4 15:09 include
drwxr-sr-x 4 jenkins jenkins 4096 Jul  4 15:09 lib64
drwxr-sr-x 3 jenkins jenkins 4096 Jul  4 15:05 share
```

**Proposed solution for netCDF**
Check for each dep if the $EBROOT<something>/lib dir exists (and is readable). If not, fallback to ```lib64```. If that doesn't exist, properly warn the user that the libdir wasn't found.

```
if os.path.exists('%s/lib' % root) and os.access('%s/lib' % root, os.R_OK):
                libs += ' -L%s/lib ' % root
            elif os.path.exists('%s/lib64' % root) and os.access('%s/lib64' % root, os.R_OK):
                libs += ' -L%s/lib64 ' % root
            else:
                self.log.warning("Can't find a libdir for dependency %s: %s/lib and %s/lib64 don't exist." % (dep, root, root))
```

**See also**
https://github.com/easybuilders/easybuild-easyconfigs/issues/9332

**Comment by casparvl** [comment]
I'll create a PR for this myself btw :) still have to make some slight changes to make it exactly what I propose above...

**Comment by akesandgren** [comment]
The paths are  EBROOTIFORT/lib/intel64 for all versions >2017 according to the installs i have.
And very likely EBROOTIFORT/lib/intel64 for all versions since v11 (i.e. since befoire they started with 20xx)

**Comment by casparvl** [comment]
@akesandgren 

Yes, I think the EasyBlock for ifort creates those links:

```
[casparl@int1 ~]$ ls -al $EBROOTIFORT
...
lrwxrwxrwx  1 jenkins jenkins    33 Jul  3 23:34 lib -> compilers_and_libraries/linux/lib
...
```

Then again, even the ```compilers_and_libraries``` is a link:

```
lrwxrwxrwx  1 jenkins jenkins    28 Jul  3 23:34 compilers_and_libraries -> compilers_and_libraries_2018
```

It's a question where 'we, the community' would prefer the link to point to I guess. The 'real' (i.e. the one containing no symlinks) in the end is

```
$EBROOTIFORT/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin
```

Yuck...

**Comment by casparvl** [comment]
Ok, I actually have a strong preference after all: any path including ```linux``` is problematic, since the way NCL 'configures' its installation is using the preprocessor to replace some variables based on defines. One of the defines (unfortunately) that is passed to the preprocessor is

```-Dlinux```

This implicitely results in

```-Dlinux=1```

and indeed, in my first tries I got

```
-lm -L$EBROOTIFORT/compilers_and_libraries/1/lib/intel64/ -lifcore -lifport
```

in my link line (yes, the ```linux``` in the directory was replaced by a ```1```).

I created a patch for the ```ymake``` file that added

```-Dlinux=linux```

to the defines. An ugly workaround, but the only thing I actually got to work.

However, if we would just use the following symlink

```
-lm -L$EBROOTIFORT/lib/intel64/ -lifcore -lifport
```

in the new EasyBlock, the whole linux-replacement problem is also gone and I don't need the ugly patch.

I believe this is by far the most pragmatic approach, and I do believe EasyBuild pushes for a fixed structure with <root>/lib, and <root>/include folders, does it not? Does this solution sound acceptable to everyone? If so, I'll test it and update the PR with it.

**Comment by casparvl** [comment]
I've implemented the above and on testing it I find that ```wrapit77``` still doesn't pass the ```rpath``` check:

```
== 2019-11-26 17:42:17,800 easyblock.py:2288 WARNING One or more required libraries not found for /home/casparl/.local/easybuild/RedHatEnterpriseServer7/2019/software/NCL/6.6.2-intel-2018b/bin/wrapit77:      linux-vdso.so.1 =>  (0x00007ffdbb9ce000)
        /hpc/sw/xalt/xalt/lib64/libxalt_init.so (0x00002b3a0010b000)
        libnetcdff.so.6 => /sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/netCDF-Fortran/4.4.4-intel-2018b/lib/libnetcdff.so.6 (0x00002b3a0034e000)
        libnetcdf.so.13 => /sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/netCDF/4.6.1-intel-2018b/lib64/libnetcdf.so.13 (0x00002b3a007db000)
        libgdal.so.20 => /sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/GDAL/2.2.3-intel-2018b-Python-3.6.6/lib/libgdal.so.20 (0x00002b3a00b6f000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002b3a022d9000)
        libiomp5.so => not found
...
```

But, it is now the only one... Checking the link line:

```
icc -ansi -O2 -O2 -xAVX -no-ipo -ip -ftz -fp-speculation=safe -fp-model source -fopenmp -fPIC -std=c99  -O2 -O2 -xAVX -no-ipo -ip -ftz -fp-speculation=safe -fp-model source -fopen
mp -fPIC -std=c99    -o wrapit77 y.tab.o lex.yy.o Symbol.o wrapit_main.o  -L/home/casparl/.local/easybuild/RedHatEnterpriseServer7/2019/software/NCL/6.6.2-intel-2018b/lib -L/sw/ar
ch/RedHatEnterpriseServer7/EB_production/2019/software/HDF5/1.10.2-intel-2018b/lib  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/JasPer/2.0.14-GCCcore-7.3.0/lib6
4  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/netCDF/4.6.1-intel-2018b/lib64  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/HDF/4.2.14-GCCcore
-7.3.0/lib  -L/home/casparl/.local/easybuild/RedHatEnterpriseServer7/2019/software/g2lib/3.1.0-intel-2018b/lib  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/g2cl
ib/1.6.0-intel-2018b/lib  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/Szip/2.1.1-GCCcore-7.3.0/lib  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/softwa
re/UDUNITS/2.2.26-intel-2018b/lib  -L/sw/arch/RedHatEnterpriseServer7/EB_production/2019/software/netCDF-Fortran/4.4.4-intel-2018b/lib -lnetcdff -lnetcdf  -L/sw/arch/RedHatEnterpr
iseServer7/EB_production/2019/software/GDAL/2.2.3-intel-2018b-Python-3.6.6/lib -lgdal   -lfl 
```

I see that somehow, the ```-L```'s for the Intel libdir is indeed completely missing. I didn't have this with my previous EasyConfig (the one that specified the path as ```.../compilers_and_libraries/...```, but that really shouldn't make a difference. Will look into it further tomorrow.
