### ISSUE TITLE
Increase timeout of CUDA install

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyblocks#1870]
The current CUDA EB fails on our Power system with

`== FAILED: Installation ended unsuccessfully (build directory: /tmp/easybuild_build-ml/CUDA/10.1.243/GCC-8.3.0): build failed (first 300 chars): run_cmd_qa: cmd   ./cuda-installer  --silent --toolkit --toolkitpath=/scratch/ws/s3248973-EasyBuild/easybuild-ml/eb/CUDA/10.1.243-GCC-8.3.0 --defaultroot=/scratch/ws/s3248973-EasyBuild/easybuild-ml/eb/CUDA/10.1.243-GCC-8.3.0  : Max nohits 300 reached: end of output  (took 9 min 35 sec)`

Running `time ./cuda-installer ...` manually shows a total time of ~13min.

However that fails anyway on power, so retrying with 10.2 running manually takes ~7min

I propose to increase the waiting time to 15 minutes

**Comment by boegel** [comment]
I'm fine with bumping the `maxhits` from 300 to say 1000 in the `run_cmd_qa` command in the CUDA easyblock to fix this. Are you up for opening a PR for this @Flamefire?

The fact that it takes a while may also be affected by a slow target filesystem, although I guess single-thread performance on POWER processors is typically a lot lower than on x86_64?

**Comment by Flamefire** [comment]
> The fact that it takes a while may also be affected by a slow target filesystem, although I guess single-thread performance on POWER processors is typically a lot lower than on x86_64?

Turned out the huge increase was due to a) a failing build with CUDA 10.1 and b) a slow filesystem due to Lustre over NFS (don't ask...)
