### ISSUE TITLE
Bundle Easyblock does not put patches into root config

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyblocks#1893]
At https://github.com/easybuilders/easybuild-easyblocks/blob/b99cc5a4dfb98cafbbd4a8827ea9bfb444724e27/easybuild/easyblocks/generic/bundle.py#L156 the patches checksums are added to the root, but the patches are not which makes e.g. the unit tests fail, see https://github.com/easybuilders/easybuild-easyconfigs/pull/9546

Should the patches be added? From the logic in the check_checksums it seems: yes

**Comment by boegel** [comment]
Spot on, fixed in #1897
