### ISSUE TITLE
Enforce flake8 styling

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyblocks#1932]
Almost all EasyBlocks fail flake8 stylechecks due to indentation and wrong regexp literals. Using hound which only checks changed lines is not enough, as adjacent lines are influenced too.

Proposal: Add a GH action that runs flake8 over all ECs and fix issues.

**Comment by Flamefire** [comment]
Fixed already

**Comment by boegel** [comment]
see #2140
