### ISSUE TITLE
failing assert in numexpr easyblock is ignored by sanity check

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#2004]
Bug reported by @jhgoebbert via https://github.com/easybuilders/easybuild-easyblocks/pull/1803#issuecomment-603972291

This is probably due to a missing `return`?

@jhgoebbert Do you remember with this easyconfig file you noticed the failing assertion?

**Comment by jhgoebbert** [comment]
This issue reports the same problem as described in detail here:  
https://github.com/easybuilders/easybuild-easyblocks/issues/2003

**Comment by boegel** [comment]
follow-up in #2003
