### ISSUE TITLE
R produced with any ICTCE toolchain doesn't use multi-threaded BLAS

### ISSUE THREAD

**Issue by pforai** [easybuilders/easybuild-easyblocks#202]
As discussed on IRC today, all R builds produced with any Intel based toolchain (hence MKL) don't use the underlying BLAS library's thread "wayness" regardless of the value set in OMP_NUM_THREADS and friends.

This is different to the behaviour that can be seen on GOOLF builds, here a few benchmarks (kindly provided by @boegel) using the following code 

```
m=matrix(rnorm(4e6),2000)
system.time(m %*% m)
```

Output from a GOOLF build:

```
user  system elapsed
 2.300  0.100  0.346
```

This shows that clearly the underlying BLAS is performing multithread since the elapsed wall time is much lower than the user time.

Output from an ICTCE build:

```
user  system elapsed
1.780  0.010  1.822
```

In this case the elapsed wall time is higher then user time and shows that nothing is being done in parallel  (as is the case with GOOLF and probably other GNU toolchains and BLAS implementations).

At this point in time it is not exactly clear what is causing this to happen and if it can be altered at run time or if this is a consequence of compile time setup.

**Comment by boegel** [comment]
I ran into this old issue while looking into an update of R (cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/5360).

The fix for this is pretty trivial, just use `BLAS_LIBS="$LIBBLAS_MT" LAPACK_LIBS="$LIBLAPACK_MT"` rather than `BLAS_LIBS="$LIBBLAS" LAPACK_LIBS="$LIBLAPACK"` in `prebuildopts` in the easyconfig file.

Currently testing this.

Are users going to be surprised by this, e.g. when they're already using multiple cores in parallel some other way?

**Comment by verdurin** [comment]
Looks like a sensible improvement to me.

Maybe include a `modloadmsg` if you're concerned about the impact of the change?

**Comment by boegel** [comment]
@verdurin I'm not sure we can explain this via a one-liner `modloadmsg` (and anything longer will not get read imho).

Maybe we should make it optional to link with a multithreaded MKL, and then use `-mt` as versionsuffix?

**Comment by verdurin** [comment]
@boegel - yes, a different configuration with a suffix would indeed make it clearer/more explicit.

**Comment by boegel** [comment]
I suggest we follow up on this in https://github.com/easybuilders/easybuild-easyblocks/pull/1292/files#r152269244

**Comment by boegel** [comment]
Further follow-up in https://github.com/easybuilders/easybuild-easyblocks/pull/1294, plan is to keep linking with sequential Intel MKL the default, but provide the option to link with multithreaded Intel MKL via a custom easyconfig parameter.
