### ISSUE TITLE
How to access 'git_config' elements in an easyblock?

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-easyblocks#2024]
I'm trying to write an EasyBlock for one of my collaboration's software packages, which is downloaded from GitHub.  For internal identification, I want to ensure that I use the Git tag used to download it, not simply the EasyBuild 'version' set in my EasyConfig.

I have not been able to find any [documentation](https://easybuild.readthedocs.io/en/latest/Implementing-easyblocks.html), nor any [examples](https://github.com/easybuilders/easybuild-easyblocks/search?q=%22git_config%22&unscoped_q=%22git_config%22) of how to access the `'git_config'` dictionary from code in an EasyBlock.  More generically, I also couldn't find examples of accessing the `sources` dictionary; from there, I could get to `'git_config'`.

I tried tracing back the class hierarchy, but once I got up to the top level easyblock.py, I got really lost in the code.  Is this something that should be relatively straightforward?  Would one of the experts be willing to point me to an example?

**Comment by smoors** [comment]
you can define git_config as follows in your easyconfig file (this example is taken from OpenFOAM-Extend-4.1-20191120-intel-2019b-Python-2.7.16.eb):
```
sources = [{
    'filename': '%%(name)s-%%(version)s-%s.tar.gz' % local_commit,
    'git_config': {
        'url': 'https://git.code.sf.net/p/foam-extend/',
        'repo_name': 'foam-extend-4.1',
        'commit': local_commit,
    },
}]
```
you can also define 'tag' and 'recursive' ('tag' and 'commit' are mutually exclusive).
you do not have to handle this in your easyblock, because this is already handled in the base easyblock (see easybuild-framework/easybuild/framework/easyblock.py).

I hope this helps, if not please don't reply in this issue but send an email to the EB mailing list:
easybuild@lists.ugent.be

**Comment by kelseymh** [comment]
I got two more useful answers to this question from the EB mailing list.

1) All of the `'git_config'` settings can be accessed from within an EasyBlock by referencing `self.cfg['sources'][0]['git_config']`, which returns the dictionary defined as in @smoors 's example above.  This assumes that `'sources'` has the target package as its first entry, which is probably a safe assumption for a package-specific EasyBlock.

2) My underlying problem was needed to get to the `git_config['tag']` value because my package wanted to use `git describe` to capture version information.  It turns out that [framework PR #3197](https://github.com/easybuilders/easybuild-framework/pull/3197) provides `keep_git_dir` as a flag in `git_config`, so that `.git` is included in the tarball.

**Comment by boegel** [comment]
Thanks *a lot* of documenting your findings here as well @kelseymh, much appreciated!

Obligatory XKCD: https://xkcd.com/979/
