### ISSUE TITLE
Incorrect download path for test data in wps.py

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyblocks#2054]
Hi,

As bugs this is pretty minor but in wps.py, the download path for geog_complete data set is currently

http://www2.mmm.ucar.edu/wrf/src/wps_files/geog_complete.tar.bz2

and it should be 

https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_complete.tar.gz

Thanks

**Comment by ocaisa** [comment]
Thanks @dithwick, confirmed and fixed in #2055
