### ISSUE TITLE
source_tmpl in PythonBundle should not try to unpack whl files

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyblocks#2086]
When `source_tmpl` in PythonBundle encounters a `.whl`-file, it will try to unpack the source, leading to the requirement of issuing `'unpack_sources': False`. PythonBundle can't and shouldn't try to unpack a `.whl`, so this should be resolved centrally.  

```python
  ('fast-ctc-decode', '0.2.5', {
        'source_tmpl': 'fast_ctc_decode-%(version)s-cp37-cp37m-manylinux1_x86_64.whl',
        'unpack_sources': False } )
```

**Comment by boegel** [comment]
This is fixed by #2366, so closing...
