### ISSUE TITLE
Sanity check fails for the d3q plugin in QE 6.4 and later as the list of binaries is wrong.

### ISSUE THREAD

**Issue by klust** [easybuilders/easybuild-easyblocks#2122]
https://github.com/easybuilders/easybuild-easyblocks/blob/1caabcf71974c608084f6fe238993eeec0afa25c/easybuild/easyblocks/q/quantumespresso.py#L487

Versions of d3q used in QE 6.4 (1.1.4 and 1.1.5), QE6.5 and QE 6.6 (1.1.7 in both versions) don't contain d3_import3py.x so the sanity check fails for those versions of QuantumESPRESSO when build with d3q (I didn't try yet with 6.6 which was released just a couple of days ago, but I did check the version of d3q).

Other executables have been added throughout versions and are missing in the list, but that is not so much a problem as it doesn't break the sanity check.

**Comment by boegel** [comment]
@migueldiascosta Is this something you can tackle as a part of your PR #2112?

**Comment by migueldiascosta** [comment]
reproduced with QE 6.6
