### ISSUE TITLE
The rpackage easyblock includes "-generic" into CFLAGS if optarch=GENERIC (on aarch64)

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyblocks#2195]
This does not go well. This example is from BiocParallel:
https://gist.github.com/terjekv/cc63120a61c9be7611c4a938c3f3396a

**Comment by terjekv** [comment]
This is only an issue due to case-sensitivity. If properly set to `GENERIC` everything works fine, but we should possibly handle unexpected values for optarch better. `GENERiC` or even `generic` seem likely to cause issues.

**Comment by boegel** [comment]
@terjekv Please open an issue to follow up on that at https://github.com/easybuilders/easybuild-framework/issues

**Comment by terjekv** [comment]
https://github.com/easybuilders/easybuild-framework/issues/3458
