### ISSUE TITLE
CGAL Easyblock checks for libs which won't exist anymore

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyblocks#2199]
From CGAL 5's source code: 

> Since Version 5.0, CGAL is now header-only by default, meaning that you do not need to build and install CGAL. Usage of CGAL as a header-only library simply amounts to, for example

https://github.com/easybuilders/easybuild-easyblocks/blob/f98e37d7bfbbfc286af54c631d822652c774db94/easybuild/easyblocks/c/cgal.py#L71

**Comment by ocaisa** [comment]
You can still build the libs though with the CMake option ` -DCGAL_HEADER_ONLY=OFF`. Probably continuing to build them is the best default right now?

**Comment by boegel** [comment]
I agree on using `-DCGAL_HEADER_ONLY=OFF` to still get those libraries, that's also what I did in the CGAL 5.2 easyconfig included in #11970.

So I'll close this, since I don't think we should change something in the CGAL easyblock...
