### ISSUE TITLE
PythonPackage: install from Git (feature request)

### ISSUE THREAD

**Issue by akutuzov** [easybuilders/easybuild-easyblocks#2261]
It is quite common that some packages are not released to PyPI, but are available at their respective Git repositories (Github, etc). Pip[ is able to install Python modules from Git repositories](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support), by using the `pip install git+https://github.com...` syntax.

However, it seems that the PythonPackage easyblock allows to pip-install Python modules only from PyPI-like repositories. This severely limits handling of dependencies and the creation of new easyconfigs in general. Is there any workaround for that? Or are there plans to implement pip+git installation workflow in EasyBuild?

**Comment by Flamefire** [comment]
EasyBuild generally does not install anything from PyPi or git directly instead it downloads the archive, unpacks it and installs it from there. Reason is that this allows checksumming the sources.

Hence all you need is to give it a different value for `source_urls` and it _just works_

**Comment by ocaisa** [comment]
If the package does not have an official release, EasyBuild can also handle this. You can find documentation on this at https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html?highlight=git_config#downloading-from-a-git-repository and specifically for python extensions at https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#extensions

**Comment by boegel** [comment]
Do let us know if this helps you @akutuzov (and if it does, please close the issue).

**Comment by akutuzov** [comment]
Thanks @ocaisa, your suggestion did work.
I am indeed  dealing with Python packages which do not have official releases (in the form of versioned archives). [NVIDIA dlllogger](https://github.com/NVIDIA/dllogger) is an example of such a package. Specifying sources in the easyconfig as follows does its job fine:
```
sources = [{
    'filename': 'dllogger.tar.gz',
    'git_config': {
        'url': 'https://github.com/NVIDIA',
        'repo_name': 'dllogger',
        'tag': 'master',
    },
}]
```
