### ISSUE TITLE
enhanced extension filter for Python packages causes trouble for netcdf4-python sanity check

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#2265]
The enhanced extension filter for Python packages made in #2224 causes trouble for `netcdf4-python-1.5.3-intel-2020a-Python-3.8.2.eb`:

```
== 2020-12-03 20:44:05,145 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: command "mpirun -n 1 PYTHONNOUSERSITE=1 python -c "import netCDF4"" failed; output:
[proxy:0:0@node3406.kirlia.os] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:128):
execvp error on file PYTHONNOUSERSITE=1 (No such file or directory)
```

We should set `$PYTHONNOUSERSITE` to `1` some other way, and make sure its set *again* after the environment is reset in the sanity check step...

cc @Flamefire

**Comment by Flamefire** [comment]
The problem here is that we must make sure it is set for all sanity checks and for the skip check. I don't know where a good place for that would be.

**Comment by boegel** [comment]
I'm rolling back the change from #2224 in #2267, I don't want this to block the release of EasyBuild v4.3.2...

**Comment by Flamefire** [comment]
@boegel Could you then look into a proper implementation of that? Because now we have a possible bug in at least `--skip` in that it considers user packages while the installed version and the pip check does not and hence might fail. At least an issue should be opened to not forget it.

**Comment by boegel** [comment]
We should definitely follow up on this, yes. Please open an issue to keep track of why we should set `$PYTHONNOUSERSITE` (and refer to the initial attempt to do so which was rolled back)
