### ISSUE TITLE
Including FlexiBLAS as the default BLAS in foss will require easyblock changes

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#2421]
A first search  indicates (at least):

- [CMakeMake](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/cmakemake.py) (see issue #2420)
- ~[numpy](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/n/numpy.py)~ (no change needed to link with FlexiBLAS, cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/12935)
- [SuperLU](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/s/superlu.py)
- ~[ScaLAPACK](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/s/scalapack.py)~ (fixed in ~#2427~)
- [LAPACK](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/l/lapack.py)
- [MXNet](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/m/mxnet.py)
- [AMBER](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/a/amber.py)
- [GAMESS-US](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/g/gamess_us.py)
- [WIEN2k](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/w/wien2k.py)

**Comment by ocaisa** [comment]
I think the numpy one in particular needs to be tackled before we merge the SciPy bundle for 2021a

**Comment by boegel** [comment]
As discussed in today's EB conf call: we should also come up with a way to detect unintentional direct linking to libraries like OpenBLAS, probably by enhancing the sanity check in framework, perhaps specifically for toolchains that include `FlexiBLAS` as a component?
We can definitely leverage some of the existing stuff that is used for the RPATH sanity check...

**Comment by boegel** [comment]
@ocaisa The `numpy` easyblock doesn't need any changes at all to link correctly with `FlexiBLAS`, verified with https://github.com/easybuilders/easybuild-easyconfigs/pull/12935 .

**Comment by branfosj** [comment]
Building R (4.1.0) in 2021a I get:
> WARNING: R will be built with generic BLAS, which will result in poor performance.

So, flexiblas is not being detected / used.

**Comment by branfosj** [comment]
> 
> 
> Building R (4.1.0) in 2021a I get:
> 
> > WARNING: R will be built with generic BLAS, which will result in poor performance.
> 
> So, flexiblas is not being detected / used.

The R configure script has a library flag (`-lopenblas`, etc.) to BLAS library name translation section. This does not know about FlexiBLAS and the default is to identify it as a generic BLAS library. The R easyblock picks this up as an issue and warns us.

**Comment by boegel** [comment]
@ocaisa Should we still keep this open?

**Comment by ocaisa** [comment]
Well, since we check for linking to openblas now, I think this can be closed. The issue will present it self when a pr is made for the relevant easyblocks
