### ISSUE TITLE
_should_unpack_source in PythonPackage breaks if there are no sources

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyblocks#2441]
https://github.com/easybuilders/easybuild-easyblocks/blob/2c20ad0899067d91c4ac05aade254903249a075c/easybuild/easyblocks/generic/pythonpackage.py#L425-L434

assumes there is at least one source, either a string or a list. But e.g. MATLAB-Engine doesn't use its own sources at all so these are now broken.

Simple fix we check is there are no sources, then `return False`

**Comment by boegel** [comment]
`_should_unpack_source` is only in `develop`, so that's definitely a regression compared to the last EasyBuild release, so worth fixing ASAP (thanks for the PR!)
