### ISSUE TITLE
OpenMPI: sanity check fails sometimes

### ISSUE THREAD

**Issue by robert-mijakovic** [easybuilders/easybuild-easyblocks#2443]
During OpenMPI is built, one can disable ORTE and use other RTE such as PMIX. 
As a consequence, no mpirun is being generated which leads to failed sanity check.
The sanity check complains that no mpirun is generated and thus the module is not generated.

**Comment by boegel** [comment]
@robert-mijakovic How are you disabling ORTE, just by customizing `configopts`?

If you do that, you should also customize `sanity_check_paths` I guess, unless we make the custom easyblock for `OpenMPI` a bit smarter...

**Comment by boegel** [comment]
@robert-mijakovic Do we need to keep this issue open? Should we change something in the central OpenMPI easyblock?

**Comment by robert-mijakovic** [comment]
@boegel I think this is no longer relevant.
Nobody except us seemingly used PRRTE with OpenMPI 4.x.
In OpenMPI 5.x, PRRTE is the default RTE and it comes with mpirun.
https://github.com/easybuilders/easybuild-easyblocks/pull/2709
