### ISSUE TITLE
Python-3.9.5-bare: No module named '_ssl'

### ISSUE THREAD

**Issue by robert-mijakovic** [easybuilders/easybuild-easyblocks#2466]
Sanity check fails on our CentOS 8.
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/build/Python/3.9.5/GCCcore-10.3.0-bare): build failed (first 300 chars): Sanity check failed: sanity check command python -c 'import _ssl' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_ssl'
) (took 8 min 56 sec)
```
@migueldiascosta

**Comment by boegel** [comment]
@robert-mijakovic This could be related to the new `OpenSSL` wrapper...

Can you check what was installed there? Is it symbolic links to the system OpenSSL, or was a from-source build triggered for the `OpenSSL-1.1.eb` easyconfig?

Can you share the log file for the failing `Python` build, to look for clue as to why `_ssl` is missing?

**Comment by robert-mijakovic** [comment]
From the log and looking into files i would say it was built from source.

Sure, please find the [OpenSSL-1.1.log](https://gist.github.com/robert-mijakovic/0f5d377206de69d4024f841d23683d33#file-easybuild-openssl-1-1-20210610-145416-log)

**Comment by boegel** [comment]
@robert-mijakovic I mean the Python log, otherwise we can't tell what the problem is with the `_ssl` component...

**Comment by Mormacill** [comment]
@boegel Let me provide you a [Python 3.9.5 build log](https://gist.githubusercontent.com/Mormacill/0d810e88d9716f01e2aadbd530f10727/raw/9cdca36a2acc81487b9dc86eb5e61c45a682be3e/easybuild-Python-3.9.5-20211110.003046.TnqUd.log) because I am running into the same failing sanity check.

**Comment by branfosj** [comment]
Comparing the build log from @Mormacill with mine I suspect that we need to add `pkg-config` as a build dependecy.

I have:
```
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking for X509_VERIFY_PARAM_set1_host in libssl... yes
checking for --with-ssl-default-suites... python
checking for --with-builtin-hashlib-hashes... md5,sha1,sha256,sha512,sha3,blake2
```

Compared to:
```
checking for x86_64-pc-linux-gnu-pkg-config... no
checking for pkg-config... no
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
checking for --with-ssl-default-suites... python
checking for --with-builtin-hashlib-hashes... md5,sha1,sha256,sha512,sha3,blake2
```

@Mormacill and @robert-mijakovic Does https://github.com/easybuilders/easybuild-easyconfigs/pull/14316 solve the issue for you?

**Comment by Mormacill** [comment]
Looks good so far, the build [succeeds.](https://gist.githubusercontent.com/Mormacill/bbebc8da6d336e9d9818dccf36d54ed7/raw/57d11d1ecdc16d3d2e7227b025723a134b9730db/easybuild-Python-3.9.5-20211110.113429.log)
Thanks @branfosj for your fast response and solution!
