### ISSUE TITLE
TBB and TensorFlow easyblocks fails for --module-only

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyblocks#2471]
I'm doing multiple module trees (on the same installation) and doing a --module-only for the TBB easyblock fails as it leaves the `libpath` variable set to `"UNKNOWN"`
Similarly, TensorFlow fails with
```
ERROR: Build of /apps/easybuild-easyconfigs/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'UNKNOWN' in /apps/Alvis/software/TensorFlow/2.3.1-fosscuda-2020a-Python-3.8.2\nsanity check command None -c 'import tensorflow' exited with code 127 (output: /bin/bash: None: command not found\n)\nsanity check command None -c 'from tensorflow.pyth")
```

**Comment by Flamefire** [comment]
TF fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/2522
TBB fixed with #2539

**Comment by Micket** [comment]
Works. Seems like there are likely a few easyconfigs that need the same fix as TF though.

**Comment by Flamefire** [comment]
Just report them as they come up :)
