### ISSUE TITLE
Bazel and Java > 13

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyblocks#2495]
https://github.com/bazelbuild/bazel/commit/0216ee54417fa1f2fef14f6eb14cbc1e8f595821

The patch below applies cleanly to all versions of Bazel on Easybuild from 3.6.0 to 4.1.0 as of June, 2020:

https://github.com/bazelbuild/bazel/commit/0216ee54417fa1f2fef14f6eb14cbc1e8f595821.patch

**Comment by boegel** [comment]
replaced by https://github.com/easybuilders/easybuild-easyconfigs/issues/13274
