### ISSUE TITLE
Samples installation in CUDAcore causes failure

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyblocks#2497]
During the install of CUDAcore 11.3.1 the installation of the samples has the following error:
```
[ERROR]: Failed to update permissions for /rds/bear-apps/devel/eb-sjb-up/tmp/CUDAcore/11.3.1/system-system//NVIDIA_CUDA-11.3_Samples/1_Utilities
```
(that is the buildpath).

This causes CUDA to remove everything installed. I've tested with a different buildpath (GPFS storage, `/dev/shm`, and local disk `/scratch`) and that also fails.

If I do not install the samples (and removing the sanity check) then the installation completes.

**Comment by Micket** [comment]
Is this unique to POWER?

**Comment by branfosj** [comment]
No. I'm seeing it on both x86_64 and POWER. I already had `CUDAcore11.3.1.eb` installed from before sample installation was added to the CUDA easyblock (#2374).

**Comment by branfosj** [comment]
I'm seeing the same issue with:
* `CUDAcore-11.3.0.eb`
* `CUDAcore-11.2.2.eb`
* `CUDAcore-11.2.1.eb`
* `CUDAcore-11.1.1.eb`
* `CUDAcore-11.0.2.eb`

**Comment by Micket** [comment]
```bash
eb CUDAcore-11.3.0.eb --include-easyblocks-from-pr 2374 --rebuild
```
using latest `eb` from develop I end up with a working installation. Build dir is on a ramdisk.

**Comment by branfosj** [comment]
I've solved my issue. If I install inside a slurm job the cgroup causes problems with the installation of the samples. If I direct log on to the node then these install fine.
