### ISSUE TITLE
OpenSSL-1.1.eb does not install corresponding pkg-config 

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-easyblocks#2525]
It appears that installing OpenSSL with OpenSSL-1.1.eb does not include the corresponding pkg-config files:
```
$ ml
Currently Loaded Modules:
  1) GCCcore/10.3.0   2) OpenSSL/1.1   3) pkg-config/0.29.2-GCCcore-10.3.0

$ pkg-config --libs --cflags openssl
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found

$ echo $PKG_CONFIG_PATH
(empty return)
```
This is not the expected behaviour and crops up when I tried to install `Rust-1.52.1-GCCcore-10.3.0.eb`

**Comment by Micket** [comment]
Note: We should generate new ones, not symlink, as we are doing a bit of a rename trick with the symlinks (for openssl11)

> > (maybe we should symlink in the pkgconfig files as well?)
> 
> Those files cannot be symlinked, we would have to re-create them with the appropriate contents.
> _Originally posted by @lexming in https://github.com/easybuilders/easybuild-easyblocks/issues/2429#issuecomment-842340663_

**Comment by Flamefire** [comment]
Required files:

- /usr/lib64/pkgconfig/libssl.pc
- /usr/lib64/pkgconfig/openssl.pc
- /usr/lib64/pkgconfig/libcrypto.pc

@lexming In what sense? Probably replacing the prefix might be enough already?

**Comment by Micket** [comment]
For e.g. Centos7 using `openssl11-devel` we'd need to change the Libs and Cflags parts as well; `Libs: -L${libdir} -L${libdir}/openssl11 -lcrypto` and `Cflags: -I${includedir} -I${includedir}/openssl11` won't be correct. Would be cleaner just to generate a file that simply fits the paths we use in the wrapper rather than modifying an existing PC file.

**Comment by sassy-crick** [comment]
It looks like that Debian/Ubuntu have the files here:
* /usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc
* /usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
* /usr/lib/x86_64-linux-gnu/pkgconfig/libcrypto.pc
Just so you know.

**Comment by Flamefire** [comment]
@Micket Yeah, looks like it. For reference:

```
$ cat /usr/lib64/pkgconfig/openssl.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 1.0.2k
Requires: libssl libcrypto

$ cat /usr/lib64/pkgconfig/libssl.pc 
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 1.0.2k
Requires: libcrypto
Libs: -L${libdir} -lssl
Libs.private: -ldl -lz -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto
Cflags: -I${includedir} -I/usr/include

$ cat /usr/lib64/pkgconfig/libcrypto.pc 
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib64
includedir=${prefix}/include
enginesdir=/usr/lib64/openssl/engines

Name: OpenSSL-libcrypto
Description: OpenSSL cryptography library
Version: 1.0.2k
Requires: 
Libs: -L${libdir} -lcrypto
Libs.private: -ldl -lz
Cflags: -I${includedir}
```
