### ISSUE TITLE
Hardcode MKL Path in EBs breaks starting with imkl 2021.x

### ISSUE THREAD

**Issue by SebastianAchilles** [easybuilders/easybuild-easyblocks#2526]
In `imkl < 2021` the libs are located in
```
$EBROOTIMKL/mkl/lib
```
This changed with `imkl >= 2021` as a  new directory structure was introduced which includes the version number:

```
$EBROOTIMKL/mkl/2021.2.0/lib
```

A handful of EasyBlocks use the following logic where the location of `imkl` is hardcoded:
```
imkl_root = get_software_root('imkl')
if imkl_root:
    imkl_include = os.path.join(imkl_root, 'mkl', 'include')
```
This breaks with `imkl >= 2021`. Instead these EasyBlocks should use:
```
imkl_root = get_software_root('imkl')
if imkl_root:
    imkl_include = os.path.join(os.getenv('MKLROOT'), 'mkl', 'include')
```

Affected EasyBlocks:
- [x] `amber.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2527
- [x] `berkeleygw.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2528
- [x] `cp2k.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2529
- [x] `freefem.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2530
- [x] `gromacs.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2531
- [x] `numexpr.py` https://github.com/easybuilders/easybuild-easyblocks/pull/2523 https://github.com/easybuilders/easybuild-easyblocks/pull/2532

**Comment by boegel** [comment]
@SebastianAchilles All PRs merged, so I guess this can be closed?

**Comment by SebastianAchilles** [comment]
Closing this issues as all PRs have been merged.
