### ISSUE TITLE
tensorflow.py: cuda_root points to wrapper "CUDA" package instead of "CUDAcore" that actually contains includes and libraries?

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyblocks#2546]
I must be missing something here, because I can't make sense of this, and I don't understand how any of this has worked for anyone else. We are doing:

https://github.com/easybuilders/easybuild-easyblocks/blob/d5ec5bd9f85ccfda4fbc7c391a30dfd0b64aff2f/easybuild/easyblocks/t/tensorflow.py#L487

but, `CUDA` is just the wrapper and it just depends on `CUDAcore` so, surely, that path is useless. But, it's used in plenty of places throughout the block
https://github.com/easybuilders/easybuild-easyblocks/blob/d5ec5bd9f85ccfda4fbc7c391a30dfd0b64aff2f/easybuild/easyblocks/t/tensorflow.py#L581
https://github.com/easybuilders/easybuild-easyblocks/blob/d5ec5bd9f85ccfda4fbc7c391a30dfd0b64aff2f/easybuild/easyblocks/t/tensorflow.py#L593

This can't possibly be correct? I'm currently getting build failures because it can't find `cublas_api.h`, but I'm just surprised this would have gone undiscovered, so I feel I'm just missing something obvious here.

**Comment by Flamefire** [comment]
At that time we didn't had CUDAcore. So this is why this has worked

**Comment by Micket** [comment]
@branfosj pointed out that it's supposed to work thanks to altroot already. But if you have rebuilt the CUDA module recently (which I had), then that got broken due to; https://github.com/easybuilders/easybuild-easyblocks/pull/2485

So, this is a non-issue then. In case anyone else hits this bug, make sure to rebuild your CUDA modules with the latest EB
