### ISSUE TITLE
Version match issue with Siesta EasyBlock

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyblocks#2551]
Hi,

I'm trying to write an easyconfig file for Siesta 4.1.5 but despite versions after 4.1-b2 no longer having a configure file to run, the easyblock is still trying to run the configure file and I'm seeing the error:

`/bin/bash: ../Src/./configure: No such file or directory`

The easyblock has:

```
if loose_ver < LooseVersion('4.1-b2'):
 # run configure 
else:
# there's no configure on newer versions
```
If I change the version to 4.2 (just as an experiment), it starts building.

I get the sense that LooseVersion may be failing to make an adequate comparison between 4.1-b2 and 4.1.5 so what should I do?

Thanks for your help

**Comment by akesandgren** [comment]
I have a patch to handle that plus a build problem with newer siesta versions. The problem is that LooseVersion in Python3 only handles numerical values.

I'll make a PR for it.

**Comment by dithwick** [comment]
Perfect, thanks @akesandgren !

**Comment by akesandgren** [comment]
Also see https://github.com/easybuilders/easybuild-easyconfigs/pull/13774

**Comment by dithwick** [comment]
Thanks @akesandgren, the combination of the updated easyblock and the easyconfig file worked for me. I also modified the easyconfig to build against intel/2020a which seemed to work fine. The tests ran slightly quicker for intel/2020a on my desktop (1hr 20 compared to 1hr 33 for foss/2020a when the tests are run on two cores). I can submit a PR for the easyconfig if you think it's worth it.

**Comment by akesandgren** [comment]
Please do if you have the time.

**Comment by dithwick** [comment]
Intel 2020a version of easyconfig https://github.com/easybuilders/easybuild-easyconfigs/pull/13780
