### ISSUE TITLE
MUMmer easyblock corrupts binaries by running apply_regex_substitutions

### ISSUE THREAD

**Issue by bedroge** [easybuilders/easybuild-easyblocks#2629]
I ran into weird issues with a PR for a toolchain bump of the existing MUMmer easyconfig, see:
https://github.com/easybuilders/easybuild-easyconfigs/pull/14474

The resulting executable doesn't work at all:
```
$ file ./mummer
./mummer: ERROR: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked error reading (Invalid argument)

$ ./mummer
Segmentation fault (core dumped)
```

After some debugging, I found that the installation step does a `apply_regex_substitutions` on all files in the build directory, including binaries:
https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/m/mummer.py#L75

**Comment by bedroge** [comment]
Another thing that I noticed while looking into this, is that the MUMmer Makefile overwrites some variables (e.g. `CFLAGS`, `CXXFLAGS`, `LDFLAGS`, etc). It might be good to change this as well.

**Comment by boegel** [comment]
@deniskristak Can you take a look at solving the problems that have been uncovered here?

* don't patch binary files with `apply_regex_substitutions` in MUMmer easyblock
* remove `prepend_paths` statement to add `bin` to `$PATH` (already done by default)
* make sure that build is done with `$CXXFLAGS` as specified by EasyBuild
* add sanity check command to MUMmer easyblock (`mummer --help`?)
