### ISSUE TITLE
Revisit default use of `ld.gold` in binutils easyblock

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#2657]
Someone mentioned in Slack that `ld.gold` is no longer being actively developed, so we should probably switch (back) to `ld.bfd` as the default.

**Comment by boegel** [comment]
The question here is when we flip the default.
Only for future GCC versions (> 11.2.0)?
Only in EasyBuild v5.0?

There may be some fallout of making a switch like this. Maybe we need an EasyBuild configuration option to control this?
