### ISSUE TITLE
ScaLAPACK header files no longer installed in include/

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#2715]
Since we made the switch to CMake for ScaLAPACK >= 2.1.0 (cfr. #2205), the header files (`include/` subdir) are no longer being installed...

**Comment by boegel** [comment]
@akesandgren Thoughts on this?

**Comment by akesandgren** [comment]
The debian packaging does not contain any include files, their own (netlib) scalapack_installer does not install any include files, and, as far as I can see, all the include files we have previously installed are sclapack internal include files, so useless for users.

There is also no mention of include files in their documentation when they talk about using scalapack.

So I'd say close this as not relevant.
