### ISSUE TITLE
MATLAB easyblock doesn't handle errors during install

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyblocks#2880]
The matlab installer script always returns 0, even if it fails due to, e.g. specifying the wrong key. 
There is no way to view the reason why, because the installer doesn't output anything to stdout. I had to run the install command myself with a modified with a outputFile specified, which contained the actual errors.

We should minimum just specify the outputFile argument so that the error logs appear *somewhere*, and possibly check for any errors inside this file.

**Comment by boegel** [comment]
This is part of the reason we have a sanity check step, I remember hitting this several times in the distant past, only to discover later nothing was installed at all...
