### ISSUE TITLE
Threaded mpi should be disabled by default in SCOTCH for all toolchains

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyblocks#2972]
https://github.com/easybuilders/easybuild-easyblocks/blob/2ecd3c97fa1563c7634adf4467f5081fd2debca1/easybuild/easyblocks/s/scotch.py#L112-L115

Comment indicates that it should have been dropped a long time ago. Lets do it for EB 5.0

**Comment by boegel** [comment]
Is this specific to `SCOTCH`?

**Comment by Micket** [comment]
I forgot to say scotch, yes, specifically scotch.

**Comment by boegel** [comment]
@Micket This can be closed thanks to #3019?

**Comment by Micket** [comment]
I thought it would have been automatically since i used the "Fixes ..." syntax
