### ISSUE TITLE
MVAPICH2 build may hang if pax is installed on system

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#30]
The MVAPICH2 v1.8.1 build hangs when `pax` is installed on the system where it is being built:

``` bash
== 2012-11-22 10:16:43,595 main.fileTools DEBUG run_cmd: running cmd  ./configure 
--prefix=/apps/gent/gulpin/magnycours/software/MVAPICH2/1.8.1-GCC-4.7.2  --with-rdma=gen2 
--with-thread-package=pthreads --enable-fast --enable-shared --enable-sharedlibs=gcc 
--enable-f77 --enable-fc --enable-cxx  (in /tmp/easy/MVAPICH2/1.8.1/GCC-4.7.2/mvapich2-1.8.1)

ATTENTION! pax archive volume change required.
Ready for archive volume: 1
Input archive name or "." to quit pax.
Archive name > 
```

```
$ rpm -qa | grep pax
pax-3.4-10.1.el6.x86_64
```

My notes indicate that this has occured with OpenFOAM in the past as well. It was then fixed by simply uninstalling `pax`, but that's not really workable.

Note: this no longer occurs for the more recent 1.9a2 version of MVAPICH2, due to changes in the build procedure.

**Comment by verdurin** [comment]
This just happened for me with `OpenMPI-1.8.8-GNU-4.9.3-2.25.eb`.

**Comment by boegel** [comment]
@verdurin please try adding this to the OpenMPI easyconfig:

```python
tar_config_opts = True
```

**Comment by verdurin** [comment]
@boegel yes, that fixes it - thanks.

**Comment by rjeschmi** [comment]
this is still hanging around. I guess we should try and clean up some old easyconfigs?

**Comment by boegel** [comment]
@rjeschmi or we can try and auto detect these hangs and act accordingly... not sure if that's feasible

**Comment by rjeschmi** [comment]
Pretty sure it is expecting input at the point it stops. I haven't looked
that close, but the fix you mentioned worked for me too.
