### ISSUE TITLE
Replace `run_cmd` and `run_cmd_qa` with `run_shell_cmd`

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyblocks#3089]
The todo list for [replacing `run_cmd` and `run_cmd_qa` with `run_shell_cmd` for EB5](https://docs.easybuild.io/easybuild-v5/run_shell_cmd/).

Please make sure this issue is updated with links to the PRs for the changes. PRs can contain multiple easyblock updates, but please consider the required testing so that there is not too many tests to be done for any one PR. Also, remember that some easyblocks are also used via `easyblock = 'EB_name'` or inherited.

## `run_cmd` only

* `adf.py`: #3091
* `amber.py`: #3094
* `anaconda.py`: #3090
* `ansys.py`: #3099
* `ant.py`: #3098
* `arb.py`: #3096 ~~#3095~~
* `atlas.py`: #3103 ~~#3097~~
* `bazel.py`: #3102
* `binutils.py`: #3105
* `blacs.py`: #3104
* `boost.py`: #3100
* `bzip2.py`: #3101
* `cfdemcoupling.py`: #3151
* `charmm.py`: #3108
* `chimera.py`: #3109
* `clang.py`: #3139
* `comsol.py`: #3110
* `cp2k.py`: #3113
* `cppcheck.py`: #3111
* `cryptography.py`: #3107 
* `cudacompat.py`: #3112
* `dl_poly_classic.py`: #3152
* `dm_reverb.py`: #3153
* `dolfin.py`: #3154
* `doxygen.py`: #3114
* `dualsphysics.py`: #3293 
* `esmf.py`: #3115
* `espresso.py`: #3117 ~~#3116~~
* `faststructure.py`: #3155
* `fdtd_solutions.py`: #3156
* `flexiblas.py`: #3136
* `fluent.py`: #3135
* `freefem.py`: #3157
* `fsl.py`: #3134
* `gamess_us.py`: #3342 (having first done #3047 to eliminate use of `run_cmd_qa`)
* `gate.py`: #3133
* `gcc.py`: #3137
* `go.py`: #3132
* `gromacs.py`: #3131
* `gurobi.py`: #3130
* `hadoop.py`: #3129
* `hpl.py`: #3128
* `hpcg.py`: #3158
* `icc.py`:  #3159
* `imkl.py`: #3122
* `imod.py`: #3126 
* `impi.py`: #3124
* `intel_compilers.py`: #3127
* `ironpython.py`: #3125
* `itac.py`: #3123
* `java.py`: #3120
* `lammps.py`: #3244
* `lapack.py`: #3219
* `libint.py`: #3218
* `libqglviewer.py`: #3217
* `libsmm.py`: #3216
* `matlab.py`: #3215
* `mcr.py`: #3213
* `metis.py`: #3212
* `mono.py`: #3211
* `mrbayes.py`: #3210
* `mrtrix.py`: #3209
* `msm.py`: #3208
* `mummer.py`:  #3207
* `mxnet.py`: #3206
* `mymedialite.py`: #3205
* `namd.py`:  #3204
* `ncl.py`: #3203
* `nemo.py`: #3202
* `neuron.py`: #3201
* `nim.py`: #3200
* `numpy.py`: #3199
* `nvhpc.py`: #3198
* `nwchem.py`: #3197
* `ocaml.py`: #3243 ~~#3196~~
* `openifs.py`: #3194
* `openblas.py`: #3195
* `openssl_wrapper.py`: #3193
* `openssl.py`: #3193
* `palm.py`: #3166
* `parmetis.py`: #3167
* `perl.py`: #3162
* `petsc.py`: #3168
* `pgi.py`: #3181
* `pplacer.py`: #3185 ~~#3183~~
* `psi.py`: needed for #3214
* `pybind11.py`: #3171
* `python.py`: #3169
* `python_meep.py`: #3182
* `qscintilla.py`: #3150 
* `root.py`: #3149 
* `rosetta.py`: #3147 ~~#3148~~
* `rust.py`: #3146 
* `scalapack.py`: #3106 
* `scipion.py`: #3140
* `scotch.py`: #3141
* `sepp.py`: #3142
* `slepc.py`: #3143
* `siesta.py`: #3192
* `star_ccm.py`: #3144
* `tbb.py`: #3145
* `tensorflow_compression.py`: #3164
* `tensorflow.py`: #3165
* `tensorrt.py`: #3179
* `tinker.py`: #3180
* `totalview.py`: #3191
* `trinity.py`: #3190
* `ucx_plugins.py`: #3189
* `vep.py`: #3188
* `vmd.py`: #3187
* `vsc_tools.py`: #3138
* `wxpython.py`: #3093
* `xmipp.py`: #3092

## `run_cmd_qa`

* `abaqus.py`: #3414
* `acml.py`: #3172
* `aladin.py`: #3173
* `bisearch.py`: #3174
* `cplex.py`: #3295
* `cuda.py`: #3274
* `doris.py`: #3175 
* `geant4.py`: #3296 and #3302
* `healpix.py`: #3285 
* `maple.py`: #3286 
* `mathematica.py`: #3298
* `modeller.py`: #3292
* `molpro.py`: #3294
* `openfoam.py`: #3299
* `qt.py`: #3291
* `repeatmasker.py`: #3290
* `repeatmodeler.py`: #3289
* `samcef.py`: #3176
* `sas.py`: #3177
* `snphylo.py`: #3178
* `stata.py`: #3288
* `wien2k.py`: #3413
* `wps.py`: #3297
* `wrf.py`: #3270
* `wrf_fire.py`: #3271

## Nothing to do

* a nothing to do: `aocc.py`, `aomp.py`, `allinea.py`, `advisor.py`, `armadillo.py`
* b nothing to do: `bwa.py`, `bwise.py`, `bowtie2.py`, `bioconductor.py`, `berkeleygw.py`, `blat.py`, `blender.py`, `bowtie.py`, `bamtools.py`
* c nothing to do: `cblas.py`, `cgal.py`, `clang_aomp.py`, `code_server.py`, `cudnn.py`, `chapel.py`, `cufflinks.py`, `crispr_dav.py`, `cmake.py`
* d nothing to do: `db.py`
* e nothing to do: `extrae.py`, `eigen.py`, `epd.py`, `elsi.py`, `easybuildmeta.py`, `egglib.py`, `elpa.py`
* f nothing to do: `flex.py`, `ferret.py`, `fftw.py`, `freesurfer.py`, `foldx.py`, `fftwmpi.py`, `freetype.py`
* g nothing to do: `g2lib.py`, `gctf.py`, `ghc.py`, `g2clib.py`
* h nothing to do: `hypre.py`, `hdf5.py`, `hpcc.py`
* i nothing to do: `imkl_fftw.py`, `ifort.py`, `inspector.py`, `ipp.py`, `iccifort.py`
* j nothing to do: `jaxlib.py`
* k no easyblocks
* l nothing to do: `lua.py`, `libxml2.py`, `llvm.py`, `libdrm.py`
* m nothing to do: `mvapich2.py`, `mothur.py`, `motioncor2.py`, `metagenome_atlas.py`, `mutil.py`, `mamba.py`, `mesa.py`, `metavelvet.py`, `mpich.py`, `mumps.py`, `mtl4.py`
* n nothing to do: `numexpr.py`, `nose.py`, `nccl.py`, `netcdf_fortran.py`, `netcdf.py`, `netcdf4_python.py`, `ncurses.py`
* o nothing to do: `opencv.py`, `orca.py`, `octave.py`, `openbabel.py`, `openmpi.py`
* p nothing to do: `psmpi.py`, `pytorch.py`, `pyzmq.py`, `primer3.py`, `pasha.py`, `paraver.py`, `pbdmpi.py`, `pdt.py`, `pyquante.py`, `picard.py`, `pbdslap.py`
* q nothing to do: `quantumespresso.py`
* r nothing to do: `reticulate.py`, `r.py`, `ruby.py`, `rserve.py`, `rmpi.py`
* s nothing to do: `superlu.py`, `suitesparse.py`, `sympy.py`, `scalasca1.py`, `shrimp.py`, `swig.py`, `scipy.py`, `score_p.py`, `samtools.py`, `soapdenovo.py`
* t nothing to do: `torchvision.py`, `tkinter.py`, `tornado.py`, `tau.py`, `trilinos.py`
* u nothing to do: `ufc.py`
* v nothing to do: `velvet.py`, `vtune.py`
* x nothing to do: `xcrysden.py`, `xml.py`, `xalt.py`
* y no easyblocks
* z no easyblocks

**Comment by boegel** [comment]
Last hurdle here is the ABAQUS easyblock, which is being dealt with in:
* https://github.com/easybuilders/easybuild-easyblocks/pull/3414

(and adding a CI check to make sure that no easyblocks rely on `run_cmd` or `run_cmd_qa`...)
