### ISSUE TITLE
OpenMPI: Unknown UCC configure option

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyblocks#3222]
Trying to build OpenMPI 4.1.1 I get the error/warning that `--with-ucc` is not a known configure option.

It was added in https://github.com/easybuilders/easybuild-easyblocks/pull/2847 

@SebastianAchilles Do you remember which version has this for sure, i.e. where you found that to be missing/required/supported?

We might need to add a version check there.

**Comment by SebastianAchilles** [comment]
I think I was looking into OpenMPI 4.1.4 when I opened https://github.com/easybuilders/easybuild-easyblocks/pull/2847

**Comment by Flamefire** [comment]
This matches with my checks that this option was added in OpenMPI 4.1.4 (backported from main/5.x)
