### ISSUE TITLE
Cleanup unused easyblocks

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyblocks#3310]
In #3089 we've cleaned up unused easyblocks instead of converting the `run_cmd` / `run_cmd_qa` use to `run_shell_cmd`. There is a list of easyblocks that do not use `run_cmd` / `run_cmd_qa`, this is the ones that are unused and remove them.

Need to check for indirect use of these (via `EB_XYZ`)

**Comment by boegel** [comment]
@branfosj Is this done now?

**Comment by branfosj** [comment]
> @branfosj Is this done now?

Do you mean this or #3089?

I'd forgotten about this one. I've not finished checking for unused blocks or creating the PRs to remove the unused ones yet. I'll revisit this soon.

**Comment by branfosj** [comment]
Done in #3423
