### ISSUE TITLE
intel-compiler fails sanity check on Debian/Ubuntu

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyblocks#3345]
With the recent changes to gcc easyblock #3254 and the older change to intel_compiler easyblock #1237 and its followups, intel-compiler now fails sanity check due to an incorrect module file being generated.

```
multiarch_inc_dir, ec = run_cmd("gcc -E -Wp,-v -xc /dev/null 2>&1 | grep %s$" % multiarch_out)
```
returns
```
easybuild@b-cn1615:~$ gcc -E -Wp,-v -xc /dev/null 2>&1 | grep  x86_64-linux-gnu'$'
 /cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu2204_icelake/software/GCCcore/13.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.0/include-fixed/x86_64-linux-gnu
 /usr/include/x86_64-linux-gnu
```

resulting in an malformed CPATH being added to the module file:
```
append_path("CPATH", "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu2204_icelake/software/GCCcore/13.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.0/include-fixed/x86_64-linux-gnu
 /usr/include/x86_64-linux-gnu")
```

Simple fix is to do ```grep -v GCCcore``` at the and of the command.

**Comment by boegel** [comment]
@akesandgren Would it make sense to either use `grep -v /include-fixed/` or `grep /include/` as a more generic way of fixing this?

**Comment by akesandgren** [comment]
Yes, that's likely better.
