### ISSUE TITLE
OpenFOAM v2406 is built without cfMesh package

### ISSUE THREAD

**Issue by furstj** [easybuilders/easybuild-easyblocks#3421]
The ESI version of OpenFoam v2406 is built without cfMesh plugin. The cfMesh package was in `modules` directory up to v2312, but now ESI moved it to `plugins`. The procedure described in `plugins/README.md` does not work due to missing .git directory.

Reproduce:

    eb -r OpenFOAM-v2406-foss-2023b.eb
    cartesianMesh

This gives 'Command not found'

The information in plugins/README.md:

      cd $WM_PROJECT_DIR
      git submodule update --init --recursive

    fatal: not a git repository (or any parent up to mount point /)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by boegel** [comment]
Hmm, this probably means we'll need to download the sources for OpenFOAM v2406 via `git_config`?

@WilleBell Is this something you're up for looking into, since you contributed the easyconfig for OpenFOAM v2406 in #21036?

**Comment by furstj** [comment]
There is an additional archive in https://dl.openfoam.com/source/latest/. In the current version (v2406) ESI has three source archives:
- OpenFOAM-v2406.tgz
- OpenFOAM-plugins-v2406.tgz
- OpenFOAM-modules-v2406.tgz

It seems that "modules" are included in main archive, i.e. in OpenFOAM-v2406.tgz but "pugins" are not. May be that someone can modify the openfoam.py easyblock to (optionally?) download and install OpenFOAM-plugins-v2406.tgz.

**Comment by WilleBell** [comment]
> Hmm, this probably means we'll need to download the sources for OpenFOAM v2406 via `git_config`?
> 
> @WilleBell Is this something you're up for looking into, since you contributed the easyconfig for OpenFOAM v2406 in #21036?

Sure, I can look into it.
