### ISSUE TITLE
NONmem 7.5.1 what easyblock should i use?

### ISSUE THREAD

**Issue by rsarathi25** [easybuilders/easybuild-easyblocks#3422]
Hi everyone ,

I need help on installing easybuild with nonmem 7.5.1 , i am not sure what to give as a easyblock and need an easyconfig file .what it looks like

**Comment by boegel** [comment]
@rsarathi25 It's probably better to ask this question via the [EasyBuild Slack](https://easybuild.io/join-slack).

You'll have to give us some more info, like a link to where `NONmem` can be download, or to its installation instructions

**Comment by rsarathi25** [comment]
Ok thanks boegel
