### ISSUE TITLE
SciPy-bundle `build_type` unrecognized

### ISSUE THREAD

**Issue by VRehnberg** [easybuilders/easybuild-easyblocks#3524]
Found in https://github.com/easybuilders/easybuild-easyblocks/pull/3499 presumed to be introduced in https://github.com/easybuilders/easybuild-easyblocks/pull/3454

Examples:
 - ~[unrelated probably](https://gist.github.com/VRehnberg/19214105aee17050ddfee521095b1211)~
 - https://gist.github.com/VRehnberg/1411573f48f71c09da8d26b66647b0e7
 - https://gist.github.com/VRehnberg/1411573f48f71c09da8d26b66647b0e7

**Comment by boegel** [comment]
fixed in #3526
