### ISSUE TITLE
Loading GCC does not override cc system compiler...

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#507]
which can lead to the situation where (for example)
cc: 4.4
c++: 4.9
gcc: 4.9
g++: 4.9
which gives a nasty surprise for software that tries cc and c++ before gcc and g++ in its configuration phase, e.g. gromacs (git master). 

Gromacs uses cmake so this can be solved by setting the appropriate env vars when loading the compiler to override this behaviour (though this approach would need pushenv and a little thought before implementation)

**Comment by boegel** [comment]
@ocaisa: ping on this; should we symlink `cc` to `gcc` when installing `GCC`?

**Comment by ocaisa** [comment]
I think this is probably a site specific choice because it really is a matter of taste. At our site, I would probably say yes but I'd have to run it by our group first

**Comment by boegel** [comment]
I'd say in general, you'd expect `cc` to be the same as `gcc`?

We can certainly support this so it can be disabled easily, but I would enable it by default?

**Comment by boegel** [comment]
thoughts on this?

**Comment by ocaisa** [comment]
I'm with you, I am implementing it at JSC today

**Comment by boegel** [comment]
\o/

**Comment by ocaisa** [comment]
For us I put the alias in the easyconfig but I'm guessing you would like it added to the EasyBlock?

**Comment by boegel** [comment]
It's ok to 'break' backwards compatibility when fixing bugs, no?
I consider `cc` being picked up from the OS a bug.

Defining an alias is probably not the best solution, since aliases don't travel down to subshells (and `eb` runs commands like `make` in subshells).

So, I think we need to make `cc` a wrapper around `gcc` in GCC's `bin` subdir?

**Comment by fgeorgatos** [comment]
fyi. 
I also thought that aliases are not inheritable (and they aren't in the generic case), 
yet `module refresh` under `/etc/profile.d` is an interesting way to handle this (look at the very end):
http://lmod.readthedocs.org/en/latest/070_standard_modules.html

**Comment by boegel** [comment]
related to https://github.com/hpcugent/easybuild-framework/issues/1993

@ocaisa did you end up implementing a workaround for this?

**Comment by ocaisa** [comment]
No workaround just
```
modaliases = {'cc': 'gcc'}
```

**Comment by boegel** [comment]
But that's not enough to catch the use of `cc` in EasyBuild, since commands like `make` are run in a subshell (and aliases don't travel down subshells)?

**Comment by ocaisa** [comment]
Right...but our use case is for users not EB

**Comment by akesandgren** [comment]
Should probably have f77 and f95 linked to gfortran too

**Comment by boegel** [comment]
enhancement to GCC easyblock that symlinks `cc` & co is implemented in https://github.com/easybuilders/easybuild-easyblocks/pull/1256

**Comment by boegel** [comment]
fixed in #1256
