### ISSUE TITLE
Binary unconditionaly prepends installdir to PATH

### ISSUE THREAD

**Issue by nathanhaigh** [easybuilders/easybuild-easyblocks#801]
I've recently had a problem with writing an easyconfig for hub (https://github.com/hpcugent/easybuild-easyconfigs/pull/2249).

It boiled down to the fact that the program executables were in a `bin` subdirectory and the module file created by EasyBuild had prepended both the `bin` subdirectory and the parent directory to the `PATH`. Normally, this might not cause issues. However, with `hub` there was an executable in the parent directory, which is distributed to help installing `hub` to the relevant location. This file was called `install`.

As a result, on subsequent calls to `eb` for installing tools, it was `hub`'s `install` file which was being picked up and not the expected system's. To make matters worse, `hub`'s `install` made a call to `install` itself. Thus resulting in recursive calls to `hub`'s `install` file.

It would be good to have a way to conditionally add the `installdir` to `PATH`

**Comment by Flamefire** [comment]
I do have a very similar problem: I have some software that comes with an `install.sh` script with non-standard parameters. This script serves as a wrapper for some custom `configure` and also executes `make` and copies files. So although the software is not in binary form, it has a binary installer which makes it suitable for the `Binary` EasyBlock.

However as it installs a directory structure (containing `bin`) I don't want `PATH` to include the INSTALL_DIR.

**Comment by boegel** [comment]
This can be closed once @Flamefire's PR #1426 gets merged?

**Comment by boegel** [comment]
ok to close now that #1426 is merged (to be included in EasyBuild v3.6.1), which paths are added to `$PATH` can now be controlled via the custom easyconfig parameter `prepend_to_path`
