### ISSUE TITLE
Provide popular PETTT ACE packages, ensure they are available as a bundle

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#85]
We are almost there, look at this list: http://pettt-ace.com/

So, apparently, looking better at it #85 is a plain subset of #86, good.

**Comment by fgeorgatos** [comment]
could you change the subject of this? `as a meta-module` -> `as a bundle`? (I cannot change it anymore!)
the individual pieces are there, just a bundle is missing (someone I know is likely working on that)

**Comment by branfosj** [comment]
This is over ten years old and the original website linked to is not working. If someone has sufficient motivation for making this happen then they can open a fresh version of this issue for the latest version and actively contribute any remaining items.
