### ISSUE TITLE
Provide popular HPC-BC packages, ensure they are available as a meta-module

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#86]
(originally by @fgeorgatos)

Many are already covered really: http://www.ccac.hpc.mil/consolidated/bc/policy.php

Namely, care for: FY06-01 (almost done), FY07-02 (UNITE can help in this), FY10-02 (almost done).

**Comment by branfosj** [comment]
This is over ten years old and the original website linked to is not working. If someone has sufficient motivation for making this happen then they can open a fresh version of this issue for the latest version and actively contribute any remaining items.
