### ISSUE TITLE
R easyblock should check for ~/.Renviron

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyblocks#867]
If the user building a module has an existing `~/.Renviron`, this may set the R libs path to OS packages, which will most likely the build.

The R easyblock should check for the existence of this file and warn the user.

**Comment by boegel** [comment]
Actually, the `RPackage` easyblock should do this, and maybe even flatout refuse to install anything while `~/.Renviron` is in place?

Or can we instruct R to ignore it?

**Comment by verdurin** [comment]
Altering the R paths might violate the principle of least surprise, so I would prefer the former i.e. refusing to install in the presence of `~/.Renviron`.

**Comment by verdurin** [comment]
Anything else, such as prepending the EB path to `~/.Renviron`, might be more trouble than it's worth.

**Comment by fizwit** [comment]
It's so important to have a clean build environment and a clean OS package list.  My advice would be to create a special account for building software.

**Comment by boegel** [comment]
fixed with #3263, which will produce a warning if `~/.Renviron` is found
