### ISSUE TITLE
Drop install_amd for new versions of PGI

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-easyblocks#924]
According to https://www.pgroup.com/doc/pgirn.pdf (as of May 17th 2016), ACML is no longer bundled with PGI, so `install_amd` is meaningless for new versions. We should probably find out when exactly it was dropped (16.1, 16.3, 16.4?) and handle it in the easyblock.

**Comment by branfosj** [comment]
#3181 removes the PGI easyblock for EB5, so closing this as no longer relevant.
