### ISSUE TITLE
add support for PLASMA libraries (alternative to LAPACK)

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#93]
(old internal ticket 299)

Support should be added to build PLASMA (http://icl.cs.utk.edu/plasma/) and MAGMA (http://icl.cs.utk.edu/magma/).

These do not provide a complete LAPACK C of Fortran API, so they can't serve as a drop-in replacement for LAPACK in a toolkit.

**Comment by branfosj** [comment]
MAGMA we have support for.

For PLASMA this is a several year old request for specific piece of software and the linked website shows 2015 as the most recent release -> closed.
